### PR TITLE
LPS-181129 | Test Fix | Master

### PR DESCRIPTION
**Pull request by victorhcunha**
[LPS-181129](https://issues.liferay.com/browse/LPS-181129)

### CODE REVIEW

**Comment by victorhcunha** [comment]
ci:test:sf

**Comment by Luizcarlosqueiroz** [comment]
ci:test:forms

**Comment by victorhcunha** [comment]
the test FormsSelectFromListField#CanAllowMultipleSelections passed on ci:test:object

**Comment by Luizcarlosqueiroz** [comment]
Hey @victorhcunha! After the changes of this PR, the [Forms#EditAllFormFieldsTypesUsedBySystemSettings](https://testray.liferay.com/home/-/testray/case_results/2265224354) started to fail. Could you check this please?

**Comment by victorhcunha** [comment]
> Hey @victorhcunha! After the changes of this PR, the [Forms#EditAllFormFieldsTypesUsedBySystemSettings](https://testray.liferay.com/home/-/testray/case_results/2265224354) started to fail. Could you check this please?

Thanks, @Luizcarlosqueiroz ! It was an unnecessary change

**Comment by victorhcunha** [comment]
ci:test:forms

**Comment by victorhcunha** [comment]
ci:test:forms

**Comment by victorhcunha** [comment]
[LocalFile.FormsSelectFromListField#CanAllowMultipleSelections](https://testray.liferay.com/home/-/testray/case_results/2272532184?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayCaseName%3DCanAllowMultipleSelections%26testrayBuildId%3D2272531031%26testrayRunId%3D2272531092%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc) and 

LocalFile.Forms#EditAllFormFieldsTypesUsedBySystemSettings
--


[LocalFile.Forms#EditAllFormFieldsTypesUsedBySystemSettings](https://testray.liferay.com/home/-/testray/case_results/2272531979?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayCaseName%3DEditAllFormFieldsTypesUsedBySystemSettings%2B%26testrayBuildId%3D2272531031%26testrayRunId%3D2272531092%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)

passed on ci

**Comment by epark18** [comment]
No regressions found in forms test suite. This looks good to go. Thank you @victorhcunha

**Comment by epark18** [comment]
ci:forward

**Pull request closed without merging**
