### PR TITLE
LPS-186052 - Fix Automation | Forms | Master

### PR DESCRIPTION
**Pull request by thaiscabrals**
**Ticket:** [LPS-186052](https://issues.liferay.com/browse/LPS-186052)
**Tests:** 
- KaleoFormsNewProcess#NewProcessAppearsOnProcessBuilder
- KaleoFormsNewProcess#CanOnlyChooseOneWorkflow

### CODE REVIEW

**Comment by thaiscabrals** [comment]
ci:test:sf

**Comment by patriciajeanperez** [comment]
Hey @thaiscabrals, can you briefly explain the cause of the failure and what we are doing to fix them? Thank you!

**Comment by thaiscabrals** [comment]
ci:test:sf

**Comment by patriciajeanperez** [comment]
Hey @thaiscabrals, where can I see it?

**Comment by patriciajeanperez** [comment]
Hey @thaiscabrals, I see two tests written in the description but a fix is made only to one test. How about the other one?

Also, I think that the test is meant to create a different workflow, choose it, and choose another workflow which is Single Approver. I don't think it will fix the issue with the Publish button.

**Comment by patriciajeanperez** [comment]
Looking at the screenshot, it looks like the test doesn't see the Publish button because of the scroll. Instead of scrolling down to see the Publish button, reach out to the team to see if the scroll in the modal is a bug we want to fix. If it is, just create the bug ticket and no action is required on our end. If it is but low priority, create a bug ticket and work on a workaround. If it is not, then just fix the test. Thanks! @thaiscabrals

**Pull request closed without merging**
