### PR TITLE
LPS-199544 | Automate| Master

### PR DESCRIPTION
**Pull request by evanilson-santana**
https://liferay.atlassian.net/browse/LPS-199544

### CODE REVIEW

**Comment by evanilson-santana** [comment]
ci:test:sf

**Comment by patriciajeanperez** [comment]
Hey @evanilson-santana and @Natanaelbenvindo did we also check the other tests that use the SIDEBAR_ITEM path? Are they still passing? Thanks!

**Comment by evanilson-santana** [comment]
> Hey @evanilson-santana and @Natanaelbenvindo did we also check the other tests that use the SIDEBAR_ITEM path? Are they still passing? Thanks!

Oh, good point, I'll run those and make sure they still passing. I'll leave the HTML file on the ticket.

**Comment by evanilson-santana** [comment]
ci:test:sf

**Comment by evanilson-santana** [comment]
ci:test:object

**Comment by victorhcunha** [comment]
Resent here https://github.com/liferay-bpm-qa/liferay-portal/pull/1338

**Pull request closed without merging**
