### PR TITLE
LPS-198440 | master

### PR DESCRIPTION
**Pull request by davisaints**
**JIRA Tickets**: [LPS-198440](https://liferay.atlassian.net/browse/LPS-198440), [LPS-198436](https://liferay.atlassian.net/browse/LPS-198436)

## Reason for this refactoring:
Several steps are needed to add an object validation through the interface, as you can see [here](https://github.com/liferay/liferay-portal/blob/b54c5ef4111265563c5fc24f93312f8f5c63095a/modules/apps/object/object-test/src/testFunctional/tests/ObjectCustomValidation.testcase#L358C1-L382C4). This causes our object testing suite to take longer to execute.

## Goal:
Make the test execution of our object suite faster.

## Note: 
I left 9 tests that add custom validations through the UI:
1. ObjectCustomValidation#CanAddEntry
2. ObjectCustomValidation#CannotActiveByDefaultWhenAddValidationsGroovy
3. ObjectCustomValidation#CanUserSeeBasicInfoTab
4. ObjectCustomValidation#CanUserSeeConditionsTab
5. ObjectCustomValidation#CanValidateSystemObjectWithExpressionBuilder
6. ObjectCustomValidation#CanViewLocalizedInputChanged
7. ObjectCustomValidation#CanViewSpecificErrorWhenGroovySintaxIsIncorrect
8. ObjectCustomValidation#ErrorMessageFieldIsRequired
9. ObjectCustomValidation#LabelFieldIsRequiredOnValidation

I left CanAddEntry and CanDefineExpressionIsEmpty to cover expression and groovy type validations. And the others make asserts in validation info such as Basic Info tab, Conditions tab, etc...

### CODE REVIEW

**Comment by davisaints** [comment]
Previously tested in this [pull request](https://github.com/davisaints/liferay-portal/pull/46).

**Comment by davisaints** [comment]
This [commit](https://github.com/liferay-bpm-qa/liferay-portal/pull/1184/commits/6e3eb0b3d7b9139a512637d4ce507cde356ebf81) is necessary because virtual instance properties on the wrong line caused BAD_REQUEST when adding object validations in some tests.

**Comment by davisaints** [comment]
Previously tested in this [pull request](https://github.com/davisaints/liferay-portal/pull/46). Also, this [commit](https://github.com/liferay-bpm-qa/liferay-portal/pull/1184/commits/6e3eb0b3d7b9139a512637d4ce507cde356ebf81) is necessary because virtual instance properties on the wrong line caused BAD_REQUEST when adding object validations in some tests.

**Comment by patriciajeanperez** [comment]
ci:test:object

**Comment by davisaints** [comment]
ci:stop

**Comment by davisaints** [comment]
ci:test:object

**Comment by davisaints** [comment]
Comparison with [object suite](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=2446338363&testrayRunIdA=2447121562&statusB=2)

No related failures!

**Comment by davisaints** [comment]
Comparison with [objects suite](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=2446338363&testrayRunIdA=2447121562&statusB=2)

No related failures!

**Review by timpak — CHANGES_REQUESTED** [review]
@davisaints looks like there's a merge conflict. Can you resolve it and forward this? Great job with the refactor!

**Comment by timpak** [comment]
Also, the description the PR was a really nice touch, having that information readily available made understanding the context a lot easier and really helped explain your thought process behind the changes. I also really appreciate that you left some the tests as UI tests to ensure we maintain coverage for that flow.

**Comment by davisaints** [comment]
ci:forward

**Pull request closed without merging**
