### PR TITLE
LPS-190244 | Test fix | Master

### PR DESCRIPTION
**Pull request by Natanaelbenvindo**
[LPS-190244](https://liferay.atlassian.net/browse/LPS-190244) 
From my investigation, this test is failing because the path has changed. I left the more generic Path to solve the problem of other tests and added two click functions to solve the problem.

### CODE REVIEW

**Comment by andreefarias** [comment]
ci:test:sf

**Review by andreefarias — APPROVED** [review]

**Comment by timpak** [comment]
Hey @Natanaelbenvindo did you test this change with other tests that use this path? If so, you can forward this.

**Comment by Natanaelbenvindo** [comment]
Hey @timpak Tim, the change in path wasn't necessary. I deleted the change.

**Comment by timpak** [comment]
ci:forward

**Pull request closed without merging**
