### PR TITLE
LPS-165993 Add CanSearchFieldNameInAggregationFieldInput test

### PR DESCRIPTION
**Pull request by nkkwon**
https://issues.liferay.com/browse/LPS-165993

### CODE REVIEW

**Comment by nkkwon** [comment]
ci:test:sf

**Comment by nikki-pru** [comment]
@nkkwon, what's the final assertion for this test?

**Comment by nkkwon** [comment]
The final assertion is that the Search for the field input works as intended, but I made creating the field with using the search for field input into one macro because didn't think it would be intuitive to break up parts of that macro
image

**Comment by timpak** [comment]
@epark18 let's discuss this during our meeting with the BPM QA leads since the aggregation field test scenarios are problematic. They don't do a good job covering the acceptance criteria and honestly don't provide a lot of business value. We need to convert them into a few high value tests that cover the main use cases of the feature. I have a couple thoughts that I wanna bounce off of you.

**Comment by nikki-pru** [comment]
@timpak We were reviewing this today. Could you let us know the fate of this test? Do we continue or will we refactor later on to reflect the acceptance criteria / actual intent of the test?

**Comment by timpak** [comment]
We need to re-write the steps for this to better fit the acceptance criteria. I'm going to move the ticket back to Open and close the PR.

**Pull request closed without merging**
