### PR TITLE
LRQA-73002 | Test Automation | Master

### PR DESCRIPTION
**Pull request by sirfabios**
https://issues.liferay.com/browse/LRQA-73002

### CODE REVIEW

**Comment by sirfabios** [comment]
ci:test:sf

**Comment by epark18** [comment]
Hey @sirfabios, this is a good start but I think you need to add two more steps. Right now this test ends at clicking on the translation menu. Based on the test name _TranslationDropdownClosesAfterSelection_ this requires:

1. Clicking on another language selection.
2. Asserting that the translation dropdown is not present after making the selection

**Comment by evanilson-santana** [comment]
Hey @sirfabios are there any updates on this PR?

**Comment by sirfabios** [comment]
> Hey @sirfabios are there any updates on this PR?

Awaiting the leader's decision, whether the test will be deleted or modified because it is the same as another one already made.

**Comment by epark18** [comment]
@sirfabios hey sorry for the delay on this one. Since _TranslationDropdownClosesClickOut_ is doing the same thing based off the steps, it's best we just keep that test and rename it. I will send in a change for that. Thanks for your work on this.

**Pull request closed without merging**
