### PR TITLE
LPS-186810 | Test automation | Master

### PR DESCRIPTION
**Pull request by andreefarias**
Ticket: [LPS-186810](https://liferay.atlassian.net/browse/LPS-186810)

I created a new file JSONNotifications.macro (similar the JSONObject.macro)

Resending after rebase error.

### CODE REVIEW

**Comment by andreefarias** [comment]
Resending this [PR](https://github.com/liferay-bpm-qa/liferay-portal/pull/955) after rebase error.

**Comment by andreefarias** [comment]
ci:forward

**Comment by andreefarias** [comment]
ci:stop

**Comment by andreefarias** [comment]
ci:test:sf

**Comment by andreefarias** [comment]
ci:test:sf

**Comment by andreefarias** [comment]
ci:forward

**Review by timpak — APPROVED** [review]

**Comment by timpak** [comment]
ci:forward

**Pull request closed without merging**
