### PR TITLE
LPS-175573 | Test Fix | Master

### PR DESCRIPTION
**Pull request by victorhcunha**
Ticket:
https://issues.liferay.com/browse/LPS-175573

### CODE REVIEW

**Comment by victorhcunha** [comment]
The tab name is not showded when the layout has only one tab

**Comment by victorhcunha** [comment]
ci:test:sf

**Comment by victorhcunha** [comment]
ci:test:sf

**Comment by andreefarias** [comment]
ci:forward

**Comment by andreefarias** [comment]
Good job, @victorhcunha!

Remember that change the ticket status to `In Progress`.

**Pull request closed without merging**
