### PR TITLE
LPS-181132 | Test Fix | Master

### PR DESCRIPTION
**Pull request by JerryAdrianoo**
**Ticket Jira:**
- [LPS-181132](https://issues.liferay.com/browse/LPS-181132)

### CODE REVIEW

**Review by Luizcarlosqueiroz — APPROVED** [review]
LGTM! :tada:

**Comment by Luizcarlosqueiroz** [comment]
Hey @JerryAdrianoo ! Remember to add the index file to the LPS next time :slightly_smiling_face:

**Comment by patriciajeanperez** [comment]
ci:forward

**Comment by JerryAdrianoo** [comment]
> Hey @JerryAdrianoo ! Remember to add the index file to the LPS next time slightly_smiling_face

Sorry, my bad. I forgot to put it. Now is there.

**Pull request closed without merging**
