### PR TITLE
LPS-181928 | Test Fix | Master

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
**Ticket:** [LPS-181928](https://liferay.atlassian.net/browse/LPS-181928)

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
ci:test:sf

**Comment by Luizcarlosqueiroz** [comment]
Test were run at CI using https://github.com/Luizcarlosqueiroz/liferay-portal/pull/16

**Comment by Luizcarlosqueiroz** [comment]
ci:test:sf

**Comment by patriciajeanperez** [comment]
ci:forward

**Pull request closed without merging**
