### PR TITLE
LPS-181093 | Test fix | Master

### PR DESCRIPTION
**Pull request by alanafergs**
https://issues.liferay.com/browse/LPS-181093

### CODE REVIEW

**Comment by alanafergs** [comment]
ci:test:sf

**Comment by patriciajeanperez** [comment]
Hi Alana! I saw there are still a number of tests that use DataEngine.assertFieldRepeated. Did you check to see if those were working before updating the macro?

**Comment by alanafergs** [comment]
@patriciajeanperez Oh, I'm sorry! In fact, I forgot to check the tests that use this macro before submitting the PR. I'll do it right now and I can resend it. Thanks for the reminder!

**Comment by alanafergs** [comment]
ci:reopen

**Pull request closed without merging**
