### PR TITLE
LPS-195275 | master

### PR DESCRIPTION
**Pull request by davisaints**
**JIRA Ticket: [LPS-195275](https://liferay.atlassian.net/browse/LPS-195275)**

## Root cause of this issue:
Cannot manipulate a Workflow when the option "Allow Administrators to Publish and Edit Workflows" is not enabled on a virtual instance

## Solution:
Do not run the tests on a virtual instance

### CODE REVIEW

**Comment by davisaints** [comment]
ci:test:workflow

**Comment by davisaints** [comment]
ci:stop

**Comment by davisaints** [comment]
ci:test:workflow

**Comment by davisaints** [comment]
The tests passed! @patriciajeanperez

**Comment by patriciajeanperez** [comment]
ci:forward

**Pull request closed without merging**
