### PR TITLE
LPS-185843 | Test Fix | Master

### PR DESCRIPTION
**Pull request by victorhcunha**
[LPS-185843](https://issues.liferay.com/browse/LPS-185843)

### CODE REVIEW

**Comment by victorhcunha** [comment]
ci:test:sf

**Review by timpak — CHANGES_REQUESTED** [review]
@victorhcunha you should look at the step to understand the purpose of the test. 
`And given an object with an attachment field is created`
The step states that we're supposed to create an object with a text field. By changing the field to a text field, you're changing the purpose of the test. You need to understand the purpose of the test when fixing them, otherwise you risk altering our test coverage. 

Please fix how the entry is created.

**Comment by victorhcunha** [comment]
Hi @timpak !
Sorry, the fix was really incorrect. The entry type confused me.
Now I sent the correction.

**Comment by victorhcunha** [comment]
ci:test:sf

**Comment by victorhcunha** [comment]
ci:test:sf

**Review by timpak — APPROVED** [review]

**Comment by timpak** [comment]
ci:forward

**Comment by victorhcunha** [comment]
ci:forward

**Comment by victorhcunha** [comment]
ci:forward:force

**Pull request closed without merging**
