### PR TITLE
LPS-185904 | Refactor test to remove path

### PR DESCRIPTION
**Pull request by victorhcunha**
[LPS-185904](https://issues.liferay.com/browse/LPS-185904)

### CODE REVIEW

**Comment by victorhcunha** [comment]
ci:test:sf

**Comment by victorhcunha** [comment]
Waiting for #861

**Review by timpak — CHANGES_REQUESTED** [review]
Hey @victorhcunha, the changes are fine but can you enable signing your commits? 

If you already have it set up, you just need to re-commit these. You can forward this once you do so

**Comment by victorhcunha** [comment]
ci:forward

**Pull request closed without merging**
