### PR TITLE
LPS-175200 | Test Automation | Master

### PR DESCRIPTION
**Pull request by victorhcunha**
Ticket:
https://issues.liferay.com/browse/LPS-175200

### CODE REVIEW

**Comment by victorhcunha** [comment]
ci:test:sf

**Comment by victorhcunha** [comment]
ci:test:sf

**Comment by victorhcunha** [comment]
ci:test:object

**Comment by victorhcunha** [comment]
ci:test:sf

**Comment by epark18** [comment]
ci:forward

**Pull request closed without merging**
