### PR TITLE
LPS-165989 Add AllFieldsFromRelatedObjectAreDisplayedWhenFilteringDateFields test

### PR DESCRIPTION
**Pull request by nkkwon**
https://issues.liferay.com/browse/LPS-165989

### CODE REVIEW

**Comment by nkkwon** [comment]
ci:test:sf

**Comment by epark18** [comment]
@nikki-pru

**Comment by nikki-pru** [comment]
@nkkwon per our conversation:
1. Set the creation of two objects in a `for` loop to clean up and it makes it easier to see that there were two of the same things being created.
2. For the layout task, either break it up into "Create the layout" and "Set the layout" or expand the task description so it's more descriptive of what's going on.

Thanks!

**Comment by nkkwon** [comment]
ci:test:sf

**Comment by nikki-pru** [comment]
@epark18 and @timpak 
This looks good to me.

For general usage though, I would suggest changing the ObjectPortlet.viewEntry to reflect that it's **asserting** the entry. `View` denotes seeing but doesn't convey whether it's an assert present or assert not present. A macro name change to 'assertEntry' might be better.

**Comment by timpak** [comment]
We need to re-write the steps for this to better fit the acceptance criteria. I'm going to move the ticket back to Open and close the PR.

**Pull request closed without merging**
