### PR TITLE
LPS-174787 | Test Fix | Master

### PR DESCRIPTION
**Pull request by abhnerramos**
Ticket:
https://issues.liferay.com/browse/LPS-174787

ObjectActions#CanTriggerActionWithExpressionByUpdatingEntry

### CODE REVIEW

**Comment by abhnerramos** [comment]
ci:test:sf

**Comment by abhnerramos** [comment]
ci:test:sf

**Comment by epark18** [comment]
ci:forward

**Comment by abhnerramos** [comment]
> @abhnerramos thank you and good job on this fix! My only request is when you do test fixes or anything related to automation is to attach your local test results on the ticket. This is just so anyone can easily see your test report and there's a record of it passing locally with the change.

Ok @epark18 ! I will keep an eye on that, thanks for the feedback!!

**Pull request closed without merging**
