### PR TITLE
LPS-193345 | Master

### PR DESCRIPTION
**Pull request by davisaints**
**JIRA Ticket:** [LPS-193345](https://liferay.atlassian.net/browse/LPS-193345)

## Root cause of this failure:
After [this](https://liferay.atlassian.net/browse/LPS-191374) change we need to allow manual membership management. 

## Solution:
I'm just adding a step to enable this setting.

### CODE REVIEW

**Comment by davisaints** [comment]
ci:test:sf

**Comment by patriciajeanperez** [comment]
Same here, can you attach the html file? Thank you! @davisaints

**Comment by davisaints** [comment]
Done! @patriciajeanperez

**Comment by patriciajeanperez** [comment]
ci:forward

**Comment by davisaints** [comment]
ci:forward

**Comment by davisaints** [comment]
ci:forward:force

**Comment by davisaints** [comment]
ci:forward

**Pull request closed without merging**
