### PR TITLE
LPS-192785 | Test Fix | Master

### PR DESCRIPTION
**Pull request by victorhcunha**
[LPS-192785](https://liferay.atlassian.net/browse/LPS-192785)

### CODE REVIEW

**Comment by victorhcunha** [comment]
ci:test:sf

**Comment by victorhcunha** [comment]
ci:test:sf

**Review by timpak — CHANGES_REQUESTED** [review]
@victorhcunha, if we're just going to use one path for both fields and object definitions, we should rename the path. 

Can you change the path name from OBJECT_LABEL_COLUMN to GENERIC_LABEL_COLUMN? You'll need to change its usage across all of our tests. Use two commits, one to change to name of the path `Rename` and the second commit to apply your changes, `Apply`.

Once you test your changes against the affected tests, you can forward this.

**Comment by victorhcunha** [comment]
ci:forward

**Pull request closed without merging**
