### PR TITLE
LPS-186816 - Fix Automation | Master

### PR DESCRIPTION
**Pull request by thaiscabrals**
**Ticket:**
-  [LPS-186816](https://liferay.atlassian.net/browse/LPS-186816)

**Tests:** 
- CanOnlyChooseOneWorkflow
- NewProcessAppearsOnProcessBuilder

### CODE REVIEW

**Comment by thaiscabrals** [comment]
ci:test:sf

**Comment by patriciajeanperez** [comment]
@thaiscabrals Can I get an explanation on what the problem is and what we are trying to solve? Thank you!

**Comment by thaiscabrals** [comment]
The tests need a configuration in the System Settings and when running the test in the virtual instance, this configuration is not possible.
@patriciajeanperez

**Comment by thaiscabrals** [comment]
ci:test:sf

**Comment by thaiscabrals** [comment]
The property was added because when running the test in a virtual instance, it is not possible to publish a workflow in Kaleo Forms.
@patriciajeanperez

**Comment by patriciajeanperez** [comment]
ci:forward

**Pull request closed without merging**
