### PR TITLE
LPS-199354 | Delete duplicate test | Master

### PR DESCRIPTION
**Pull request by mateussandes23**
Ticket: [LPS-199354](https://liferay.atlassian.net/browse/LPS-199354)

This test is doing the same thing that `ObjectCustomValidation#CanCreateValidationUsingOldValueFunctionInSystemObject` so we opted to delete them.

### CODE REVIEW

**Comment by mateussandes23** [comment]
ci:test:sf

**Comment by patriciajeanperez** [comment]
@timpak @mateussandes23 It was intentionally moved to `ObjectCustomValidation` in [LPS-189641](https://liferay.atlassian.net/browse/LPS-189641). Can you help confirm which one we want to keep?

**Comment by timpak** [comment]
Interesting, looks like the test was added in two separate testcase files. Let's go with this approach and remove the one in `ObjectCustomValidation`

**Review by timpak — APPROVED** [review]
LGTM!

**Comment by timpak** [comment]
ci:forward

**Pull request closed without merging**
