### PR TITLE
LPS-183255 | Test Fix | Master

### PR DESCRIPTION
**Pull request by JerryAdrianoo**
**Ticket Jira:**
- [LPS-183255](https://issues.liferay.com/browse/LPS-183255)

### CODE REVIEW

**Comment by JerryAdrianoo** [comment]
ci:test:sf

**Review by Luizcarlosqueiroz — APPROVED** [review]
LGTM! :tada:

**Comment by patriciajeanperez** [comment]
Thank you, @JerryAdrianoo! Please upload passing index html files next time for the reviewer/s.

**Comment by patriciajeanperez** [comment]
ci:forward

**Comment by JerryAdrianoo** [comment]
> Thank you, @JerryAdrianoo! Please upload passing index html files next time for the reviewer/s.

Oh, sorry, my bad. I forgot to put it. Now is there.

**Pull request closed without merging**
