### PR TITLE
LPS-187359 | Test fix | Master

### PR DESCRIPTION
**Pull request by Natanaelbenvindo**
Ticket: [LPS-187359](https://liferay.atlassian.net/browse/LPS-187359) 
From my investigation, the relationship label is wrong. This is why the test is failing.

### CODE REVIEW

**Comment by Natanaelbenvindo** [comment]
ci:test:sf

**Comment by andreefarias** [comment]
ci:test:sf

**Comment by andreefarias** [comment]
ci:stop

**Comment by andreefarias** [comment]
ci:test:sf

**Comment by andreefarias** [comment]
Could you organize this PR? We need to follow the pattern.

- Update the name to LPS-XXXXX | Test fix | Master
- Update the description formatted to only LPS and a small description.

See an [example](https://github.com/liferay-bpm-qa/liferay-portal/pull/916)

cc: @Natanaelbenvindo

**Review by andreefarias — APPROVED** [review]

**Comment by andreefarias** [comment]
I'm not sure if only the name is enough to fix it, because the path searches as **contains**  (the old name has the name correctly as contains). Maybe, is necessary to a WaitForSPARefresh(); to wait for a single page totally load.

cc: @Natanaelbenvindo

**Comment by timpak** [comment]
Hey @Natanaelbenvindo is this ready to be reviewed?

cc: @andreefarias

**Comment by Natanaelbenvindo** [comment]
Upon further investigation, I found that this isn't a test fix, it's a bug.

**Pull request closed without merging**
