### PR TITLE
LPS-176844 | Test Automation | Master

### PR DESCRIPTION
**Pull request by victorhcunha**
https://issues.liferay.com/browse/LPS-176844
https://issues.liferay.com/browse/LPS-177428

ObjectFields#CanManageFormulaFieldWithView
ObjectFields#CanManageFormulaFieldWithLayout

Using macro/path from #552

### CODE REVIEW

**Comment by victorhcunha** [comment]
ci:test:sf

**Comment by victorhcunha** [comment]
ci:test:sf

**Comment by victorhcunha** [comment]
ci:test:sf

**Comment by victorhcunha** [comment]
ci:test:sf

**Comment by victorhcunha** [comment]
ci:test:sf

**Comment by victorhcunha** [comment]
ci:test:sf

**Comment by victorhcunha** [comment]
ci:test:sf

**Comment by victorhcunha** [comment]
ci:test:sf

**Comment by andreefarias** [comment]
So many tests separate related to Formula Field. I'll merge them all and send you a unique PR. Thanks!

**Comment by andreefarias** [comment]
ci:close

**Pull request closed without merging**
