### PR TITLE
LPS-197514 | master

### PR DESCRIPTION
**Pull request by davisaints**
**JIRA Tickets:**

[LPS-197514](https://liferay.atlassian.net/browse/LPS-197514), [LPS-192017](https://liferay.atlassian.net/browse/LPS-192017)

## Context:
1. About [LPS-197514](https://liferay.atlassian.net/browse/LPS-197514): As we only need to verify that, after the update, the setting to enable object entries as drafts is set to false by default,I just included this step in one of our existing upgrade tests that uses a db dump from the U33 bundle.
2. About [LPS-192017](https://liferay.atlassian.net/browse/LPS-192017): The upgrade tests were quarantined until [LPS-169398](https://liferay.atlassian.net/browse/LPS-169398) was fixed. But as it has already been fixed, I am removing them.

### CODE REVIEW

**Comment by davisaints** [comment]
ci:test:object

**Comment by davisaints** [comment]
ci:test:object:nocompile

**Comment by davisaints** [comment]
ci:test:object

**Comment by davisaints** [comment]
ci:test:object

**Comment by davisaints** [comment]
ci:test:object

**Comment by davisaints** [comment]
Only ViewPicklistAfterUpgrade7413U33 needs a fix, so I'm ignoring it. Unfortunately I didn't have time to fix it. In general, it seems good to go.

**Comment by patriciajeanperez** [comment]
@davisaints do we have a ticket for the failure in ViewPicklistAfterUpgrade7413U33?

**Comment by davisaints** [comment]
> @davisaints do we have a ticket for the failure in ViewPicklistAfterUpgrade7413U33?

Yes we have. I opened this one [LPS-199611](https://liferay.atlassian.net/browse/LPS-199611)

**Comment by patriciajeanperez** [comment]
ci:forward

**Pull request closed without merging**
