### PR TITLE
LPS-180079 | Test Automation | Master

### PR DESCRIPTION
**Pull request by victorhcunha**
[LPS-180079](https://issues.liferay.com/browse/LPS-180079) ObjectActions#CanUpdateOrderAfterUpdatingCommerceOrderEntry

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
ci:test:sf

**Comment by andreefarias** [comment]
It has been temporarily **blocked** as we may need to change the structure of the test case.

**Comment by timpak** [comment]
@andreefarias can you update the ticket with the new steps, description, test name?

**Comment by andreefarias** [comment]
I updated the ticket with the correct info related to steps, description, and test name.

cc: @timpak @victorhcunha

**Comment by timpak** [comment]
@victorhcunha can you take a look at the updated steps and make sure your test follows them? You'll need to update the strings as well.

**Comment by victorhcunha** [comment]
ci:test:sf

**Comment by andreefarias** [comment]
Good job, @victorhcunha!

LGTM! 🎉

**Review by timpak — APPROVED** [review]

**Comment by timpak** [comment]
ci:forward

**Pull request closed without merging**
