### PR TITLE
LPS-180255 Add ERC argument to Picklist macro using API

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
**Ticket:**
[LPS-180255](https://issues.liferay.com/browse/LPS-180255)

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
ci:test:sf

**Comment by timpak** [comment]
Hey @Luizcarlosqueiroz, did you check if this affects our existing picklist tests? If you already did and there aren't any issues, you can forward this

**Comment by Luizcarlosqueiroz** [comment]
Hey @timpak ! Yes, if we don't pass any value for externalReferenceCode, the Curl will be made passing an empty string and then the API will generate a random ERC for that picklist.

**Comment by Luizcarlosqueiroz** [comment]
ci:forward

**Pull request closed without merging**
