### PR TITLE
LPS-175309 | Test Fix | Master

### PR DESCRIPTION
**Pull request by JhossephG**
https://issues.liferay.com/browse/LPS-175309

### CODE REVIEW

**Comment by JhossephG** [comment]
ci:test:sf

**Comment by JhossephG** [comment]
ci:test:objects

**Comment by JhossephG** [comment]
ci:test:object

**Comment by andreefarias** [comment]
Hey @JhossephG, it's not necessary to run the `ci:test:object`. This suite is used to developers see what tests were broken.

**Comment by andreefarias** [comment]
One question, do you tested whether the tests that **don't add** Sites and Orders pass successfully?

**Comment by JhossephG** [comment]
> One question, do you tested whether the tests that **don't add** Sites and Orders pass successfully?
I'm working exactly on this now. And about the ci:test:object I need to run this routine to verify if the new macro is affecting the other tests

**Comment by JhossephG** [comment]
ci:test:object

**Comment by epark18** [comment]
ci:test:object
@JhossephG When the most recent results finish, can you analyze and make sure no regressions are caused? You may forward afterwards if it looks good

**Comment by JhossephG** [comment]
> ci:test:object
> 
> @JhossephG When the most recent results finish, can you analyze and make sure no regressions are caused? You may forward afterwards if it looks good

Perfect, I'll do this

**Comment by JhossephG** [comment]
ci:test:object

**Comment by JhossephG** [comment]
Nothing related from my changes was found

**Comment by JhossephG** [comment]
ci:forward

**Pull request closed without merging**
