### PR TITLE
LPS-168667 | Test fix | Master

### PR DESCRIPTION
**Pull request by alanafergs**
https://issues.liferay.com/browse/LPS-186978

### CODE REVIEW

**Comment by alanafergs** [comment]
ci:test:sf

**Comment by alanafergs** [comment]
ci:test:data-engine

**Comment by alanafergs** [comment]
ci:test:forms

**Comment by alanafergs** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
Hey @alanafergs, for dev PRs, send it to liferay-forms. Thanks!

**Pull request closed without merging**
