### PR TITLE
LPS-165987 Add AllFieldsFromRelatedObjectAreDisplayedWhenFilteringLongIntegerFields test

### PR DESCRIPTION
**Pull request by nkkwon**
https://issues.liferay.com/browse/LPS-165987

### CODE REVIEW

**Comment by nkkwon** [comment]
ci:test:sf

**Comment by nkkwon** [comment]
ci:test:sf

**Comment by epark18** [comment]
ci:test:sf

**Comment by epark18** [comment]
ci:forward

**Pull request closed without merging**
