### PR TITLE
LPS-165986 | Master

### PR DESCRIPTION
**Pull request by kristinonias**
https://issues.liferay.com/browse/LPS-165986

### CODE REVIEW

**Comment by epark18** [comment]
ci:test:sf

**Comment by epark18** [comment]
@nikki-pru

**Comment by timpak** [comment]
I'm taking a look at the original story ticket, [LPS-156704](https://issues.liferay.com/browse/LPS-156704), and these steps need to be modified. Unfortunately, the test scenarios were poorly written for this story so it makes this pretty complicated. We need to cover the 2nd acceptance criteria:
```
2 - Given a power user,
when managing an aggregation field,
then I must be able to add filters for the numeric (integer and long integer) fields to select data from the object

    The operators available are:

        Equals to
        Not Equals to
    This operation needs to show all fields from the related object.
```

@epark18 can you check if we actually need this test? If we do, we'll need to modify the steps and the verbiage to better reflect what's needed. I'll need to go through the automation tickets for these test scenarios when I have time to see if they actually cover what we need.

**Comment by epark18** [comment]
@timpak So, there's an existing test ObjectFields#AllFieldsFromRelatedObjectAreDisplayedWhenFilteringLongIntegerFields already in master, but it has the same problem where it's not covering the aggregation fields. That's a mistake on my part. I think I was thrown off by the story ticket being crossed out, so I went off the name of the test. 

1. I will rewrite the mentioned test to cover aggregation fields. Will probably need to take a look at more existing aggregation tests and see what needs to be reworked.
2. As for this test, I don't think it's entirely necessary since we have something pretty similar. I've noticed this a lot in Objects tests, actually. We have a lot of very similar tests where the only difference is changing the type of field.

**Comment by timpak** [comment]
We need to re-write the steps for this to better fit the acceptance criteria. I'm going to move the automation ticket back to Open and close this PR.

**Pull request closed without merging**
