### PR TITLE
LPS-175562

### PR DESCRIPTION
**Pull request by marcosvictor22**

### CODE REVIEW

**Comment by marcosvictor22** [comment]
ci:test:sf

**Comment by andreefarias** [comment]
Hey @marcosvictor22,

the goal for this testcase is to see the **new tab (Field Tab)** created when adding a **Custom Layout**. I saw that fields show only when added another tab, so that would be a bug.

**Comment by andreefarias** [comment]
I'll close this PR. Thanks!

**Comment by andreefarias** [comment]
ci:close

**Pull request closed without merging**
