### PR TITLE
LPS-178357 | Test Fix | Master

### PR DESCRIPTION
**Pull request by victorhcunha**
[LPS-178357](https://issues.liferay.com/browse/LPS-178357)

### CODE REVIEW

**Comment by victorhcunha** [comment]
ci:test:sf

**Comment by victorhcunha** [comment]
ci:test:sf

**Comment by victorhcunha** [comment]
ci:test:sf

**Review by andreefarias — APPROVED** [review]

**Comment by andreefarias** [comment]
ci:forward

**Pull request closed without merging**
