### PR TITLE
LPS-192075 | Test Fix | Master

### PR DESCRIPTION
**Pull request by victorhcunha**
[LPS-192075](https://liferay.atlassian.net/browse/LPS-192075)

### CODE REVIEW

**Comment by victorhcunha** [comment]
ci:test:sf

**Comment by victorhcunha** [comment]
ci:stop

**Comment by victorhcunha** [comment]
ci:test:sf

**Review by timpak — APPROVED** [review]

**Comment by timpak** [comment]
We probably will want to rename that path in the future since it no longer accurately describes its purpose.

**Comment by timpak** [comment]
ci:forward

**Pull request closed without merging**
