### PR TITLE
LPS-183331 | Test Fix | Master

### PR DESCRIPTION
**Pull request by victorhcunha**
[LPS-183331](https://issues.liferay.com/browse/LPS-183331)

### CODE REVIEW

**Comment by victorhcunha** [comment]
ci:test:sf

**Comment by evanilson-santana** [comment]
Hey, @victorhcunha  great job, we need just to make double-check before forward

**Review by timpak — APPROVED** [review]
@victorhcunha I'll approve this but a couple of suggestions to keep in mind for the future:
- Be careful with your capitalization. You don't need to capitalize a word like `macro` unless it's a proper noun. Also, you should double check your capitalization in words, you wrote `PAth` in 91f0eb53205cd142d83148243208afe477cb9878
- cc5b3206661ae6dc754da086611a548735b44d23 and 679b27ae79e4398a2edf761295d8ae1c056101f4 can be combined into one commit since they're making the same changes albeit in different files.
- 679b27ae79e4398a2edf761295d8ae1c056101f4
- Make sure you're using present tense. Use `Remove` instead of `Removing`

**Comment by timpak** [comment]
ci:forward

**Pull request closed without merging**
