### PR TITLE
LPS-184143 Investigate CreateObject#CanSearchObjectEntryTitleOnRelationshipField

### PR DESCRIPTION
**Pull request by GABRIELCMSANTOS**

### CODE REVIEW

**Comment by GABRIELCMSANTOS** [comment]
ci:test:sf

**Comment by timpak** [comment]
@GABRIELCMSANTOS do we still need this change? [The ticket](https://issues.liferay.com/browse/LPS-184143) was closed as `No Longer Reproducible`.

**Comment by timpak** [comment]
If we do need this change, please fix your commit message and then you can forward this. It should be:
`LPS-184143 Add WaitForElementPresent`

**Comment by GABRIELCMSANTOS** [comment]
Sorry @timpak, someone closed the ticket without notifying me. I will close the PR.

**Pull request closed without merging**
