### PR TITLE
LPS-178784 | Test Automation | Master

### PR DESCRIPTION
**Pull request by victorhcunha**
[LPS-178784](https://issues.liferay.com/browse/LPS-178784) ObjectNotifications#CanSendEmailViaActionDownload

### CODE REVIEW

**Comment by victorhcunha** [comment]
ci:test:sf

**Comment by victorhcunha** [comment]
[ci](ci:forward)

**Comment by victorhcunha** [comment]
ci:foward

**Comment by victorhcunha** [comment]
ci:forward

**Comment by victorhcunha** [comment]
ci:forward

**Comment by andreefarias** [comment]
Hey @victorhcunha, I'll close this PR, because it's already available on Master.

**Pull request closed without merging**
