### PR TITLE
Test Fix| LPS-196431 | Workflow

### PR DESCRIPTION
**Pull request by thaiscabrals**
**Ticket:** [LPS-196431](https://liferay.atlassian.net/browse/LPS-196431)
**Test:** WorkflowWebContent#ViewLargeImageAddedByNotification

### CODE REVIEW

**Comment by thaiscabrals** [comment]
ci:test:sf

**Comment by thaiscabrals** [comment]
In this test, the **_json_** and **_png_** files were created as test files, and when running the test, they couldn't be found because they were searched for as a dependency.
I moved the test case files to dependencies.

**Comment by patriciajeanperez** [comment]
ci:forward

**Comment by thaiscabrals** [comment]
ci:forward

**Comment by evanilson-santana** [comment]
ci:test:stable

**Comment by evanilson-santana** [comment]
ci:forward

**Comment by MarinhoFeliphe** [comment]
Resent here: https://github.com/liferay-workflow/liferay-portal/pull/1053

cc: @Luizcarlosqueiroz @thaiscabrals

**Comment by MarinhoFeliphe** [comment]
ci:close

**Pull request closed without merging**
