### PR TITLE
Test fix | LPS-194538

### PR DESCRIPTION
**Pull request by evanilson-santana**
https://liferay.atlassian.net/browse/LPS-194538

Testray link: https://testray.liferay.com/home/-/testray/subtasks/2412863800

So basically [this](https://github.com/liferay-objects/liferay-portal/pull/2413/commits/0b823feac3a6d0f7078ab23c4a2ff44ee3610674) PR makes changes to the filter section of the aggregation fields. With that, we need to change the relationship to no longer be a relationship with itself.

### CODE REVIEW

**Comment by evanilson-santana** [comment]
ci:test:sf

**Comment by timpak** [comment]
@evanilson-santana can we actually refactor these tests to use object entries? Right now, we're creating aggregation fields but we're not actually asserting that they're working, does that make sense? You can create a separate ticket to improve these tests.

Would it be possible to include the test improvements in this PR? If it isn't, I can review this first and we can work on the other ticket later.

**Comment by evanilson-santana** [comment]
> @evanilson-santana can we actually refactor these tests to use object entries? Right now, we're creating aggregation fields but we're not actually asserting that they're working, does that make sense? You can create a separate ticket to improve these tests.
> 
> Would it be possible to include the test improvements in this PR? If it isn't, I can review this first and we can work on the other ticket later.

Yes, we can. I'll create a test improvement ticket and include the commit on this PR, thanks!

**Comment by evanilson-santana** [comment]
Hey @timpak. After investigating more about the coverage of the aggregation field feature, I noticed that we have this test: _`CanCreateEntryWithAggregationField`_ And that the flow of adding entries to make sure that the aggregation works is missing. I believe it makes more sense to add the entry addition step to it as well.

I have three other points about the tests I fixed:

1 - These tests are without story LPS. I think I can add the LPS from the Aggregation story since it uses the aggregation field.

2 - The goals for these tests, following the logic and description, would just be to assert that the operators used when creating the field filter are available. Adding the entry addition step also makes sense to make sure the operators work.

3 - The following tests were automated:
_`IsEqualToIsAvailableForIntegerFields`_
_`IsEqualToIsAvailableForLongIntegerFields`_
_`IsNotEqualToIsAvailableForLongIntegerFields`_
_`RangeIsAvailableForDateFields`_.

I don't think it makes sense to have two tests that test the same operator, in this case "Is Equal To" just by varying the field. I think the ideal would be to exclude one of these and have only 3 testing the available operators: "Is Equal To", "Is Not Equal To" and "Range". They are the possible operators that we can use to assemble the aggregation.

**Comment by evanilson-santana** [comment]
Resent [here](https://github.com/liferay-bpm-qa/liferay-portal/pull/1185)

**Pull request closed without merging**
