### PR TITLE
LPS-190642 | Test Automation | Master

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
**Ticket:** [LPS-190642](https://liferay.atlassian.net/browse/LPS-190642)

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
ci:test:sf

**Comment by patriciajeanperez** [comment]
LGTM! @timpak

**Comment by thaiscabrals** [comment]
Just starting reviewing :)

**Comment by Luizcarlosqueiroz** [comment]
ci:test:object

**Comment by Luizcarlosqueiroz** [comment]
I noticed an issue at this macro with @thaiscabrals . I'll fix it.

**Pull request closed without merging**
