### PR TITLE
LPS-178160 | Set portal.acceptance property for tests related to the oldValue function

### PR DESCRIPTION
**Pull request by davisaints**
**JIRA Ticket**: [LPS-178160](https://issues.liferay.com/browse/LPS-178160)

### CODE REVIEW

**Comment by davisaints** [comment]
ci:test:sf

**Comment by andreefarias** [comment]
ci:forward

**Comment by andreefarias** [comment]
ci:reopen

**Comment by andreefarias** [comment]
ci:forward

**Comment by andreefarias** [comment]
ci:stop

**Comment by andreefarias** [comment]
ci:forward

**Pull request closed without merging**
