### PR TITLE
LPS-193134 | Test Fix | Master

### PR DESCRIPTION
**Pull request by victorhcunha**
[LPS-193134](https://liferay.atlassian.net/browse/LPS-193134)

### CODE REVIEW

**Comment by victorhcunha** [comment]
ci:test:sf

**Comment by andreefarias** [comment]
LGTM! 🎉

**Comment by andreefarias** [comment]
ci:forward

**Comment by andreefarias** [comment]
ci:forward

**Comment by victorhcunha** [comment]
ci:forward:force

**Comment by andreefarias** [comment]
ci:stop

**Comment by victorhcunha** [comment]
ci:test:sf

**Comment by victorhcunha** [comment]
ci:test:sf

**Comment by victorhcunha** [comment]
ci:test:sf

**Comment by andreefarias** [comment]
ci:forward

**Comment by victorhcunha** [comment]
ci:test:sf

**Comment by victorhcunha** [comment]
ci:test:sf

**Comment by victorhcunha** [comment]
ci:test:sf

**Comment by victorhcunha** [comment]
ci:forward

**Comment by victorhcunha** [comment]
ci:forward

**Comment by timpak** [comment]
@andreefarias and @victorhcunha let's hold off on this for now, we probably should go through the SF changes from Brian first before modifying the files

**Comment by evanilson-santana** [comment]
Hey, @victorhcunha, @andreefarias, and @timpak, can we try to forward it again?

**Comment by victorhcunha** [comment]
Resent with new approach here #1195
@evanilson-santana @andreefarias @timpak
Feel free to take a look

**Comment by evanilson-santana** [comment]
I'll take a look, thanks!

**Pull request closed without merging**
