### PR TITLE
LPS-195294 | master

### PR DESCRIPTION
**Pull request by victorhcunha**
[LPS-195294](https://liferay.atlassian.net/browse/LPS-195294)

### CODE REVIEW

**Comment by victorhcunha** [comment]
ci:test:sf

**Review by patriciajeanperez — CHANGES_REQUESTED** [review]

**Comment by victorhcunha** [comment]
ci:test:sf

**Review by timpak — APPROVED** [review]
LGTM!

**Comment by timpak** [comment]
ci:forward

**Pull request closed without merging**
