### PR TITLE
LPS-192080  | Test Fix | Master

### PR DESCRIPTION
**Pull request by sirfabios**
https://liferay.atlassian.net/browse/LPS-192080

### CODE REVIEW

**Comment by sirfabios** [comment]
ci:test:sf

**Comment by timpak** [comment]
@sirfabios two questions:
- Were you not able to find an existing path that works for this?
- Can we try using a less fragile path like the following?
`//div[@class='dropdown-menu autocomplete-expand show']//div[contains(text(), '${key_optionName}')`

**Comment by sirfabios** [comment]
@timpak 
- I couldn't find a path that found this exact place.
- Yes, this path is from the Object, we can fix it, if it was in a file somewhere else, only people from the other team could fix it, that would take time.

**Comment by timpak** [comment]
@sirfabios gotcha so can we try using a less fragile path like the one I suggested?

**Comment by sirfabios** [comment]
ci:test:sf

**Review by timpak — APPROVED** [review]

**Comment by timpak** [comment]
ci:forward

**Pull request closed without merging**
