### PR TITLE
LPS-179024 | Test Fix | Master

### PR DESCRIPTION
**Pull request by sirfabios**
https://issues.liferay.com/browse/LPS-179040

### CODE REVIEW

**Comment by sirfabios** [comment]
ci:test:sf

**Comment by sirfabios** [comment]
ci:test:workflow

**Comment by sirfabios** [comment]
ci:test:sf

**Comment by sirfabios** [comment]
ci:test:workflow

**Comment by sirfabios** [comment]
ci:test:workflow-metrics

**Comment by andreefarias** [comment]
ci:forward:force

**Pull request closed without merging**
