### PR TITLE
LPS-181944 ObjectActions | Test Automation | Master

### PR DESCRIPTION
**Pull request by victorhcunha**
Using macro/path from #732 
Extracting tests from #722 #692

- [LPS-181943](https://issues.liferay.com/browse/LPS-181943) ObjectActions#CanAddCommerceProductGroupEntryAfterDeletingCommerceProductEntry
- [LPS-181944](https://issues.liferay.com/browse/LPS-181944) ObjectActions#CanUpdateCommerceProductEntryAfterUpdatingCommerceProductEntry
- [LPS-180195](https://issues.liferay.com/browse/LPS-180195) ObjectActions#CanAddAccountEntryAfterCreatingAccountEntry
- [LPS-180082](https://issues.liferay.com/browse/LPS-180082) ObjectActions#CanAddAccountEntryAfterCreatingCustomObjectEntry
- [LPS-180083](https://issues.liferay.com/browse/LPS-180083) ObjectActions#CanAddAccountEntryAfterUpdatingCustomObjectEntry
- [LPS-180087](https://issues.liferay.com/browse/LPS-180087) ObjectActions#CanAddAccountEntryAfterDeletingCustomObjectEntry

The tests have been adapted to use the same macro

### CODE REVIEW

**Comment by victorhcunha** [comment]
ci:test:sf

**Comment by victorhcunha** [comment]
ci:test:sf

**Comment by andreefarias** [comment]
Nice, thanks for your job @victorhcunha!

I'll cherry-pick this PR with some others to fix conflicts. The small fixes I'll fix

**Comment by victorhcunha** [comment]
ci:test:sf

**Comment by andreefarias** [comment]
I'll close this PR. This testcase is related to this PR: #753 which was cherry-picked with others and resolved the conflict.

Thanks for your collaboration.

**Comment by andreefarias** [comment]
Hey @victorhcunha, I reopened this PR to fix some things. I'll review and request some changes.

Add only your commits in this testcase, please.

**Comment by andreefarias** [comment]
I'll review based on it: https://github.com/liferay-bpm-qa/liferay-portal/pull/753

**Pull request closed without merging**
