### PR TITLE
LPS-193156 | Test fix | Master

### PR DESCRIPTION
**Pull request by alanafergs**
https://liferay.atlassian.net/browse/LPS-193156

### CODE REVIEW

**Comment by alanafergs** [comment]
ci:test:sf

**Comment by alanafergs** [comment]
ci:test:sf

**Comment by patriciajeanperez** [comment]
ci:forward

**Comment by patriciajeanperez** [comment]
ci:forward

**Comment by patriciajeanperez** [comment]
ci:forward:force

**Pull request closed without merging**
