### PR TITLE
LPS-195691 - Automation | Objects | Master

### PR DESCRIPTION
**Pull request by thaiscabrals**
**Ticket:** [LPS-195691](https://liferay.atlassian.net/browse/LPS-195691)
**Test:** ObjectModelBuilder#CanCreateObjectEntry

### CODE REVIEW

**Comment by thaiscabrals** [comment]
ci:test:sf

**Comment by thaiscabrals** [comment]
This test can only be merged after this [PR](https://github.com/liferay-bpm-qa/liferay-portal/pull/1148).
The `ObjectAdmin.addObjectFolderViaAPI` macro has not yet been merged, which is why the SF failed.
cc. @patriciajeanperez @timpak

**Comment by patriciajeanperez** [comment]
@timpak Do we still want to add the feature flag property or just wait for the feature flag to be removed? Other than that, this PR looks good to me!

**Comment by patriciajeanperez** [comment]
@thaiscabrals, we just need to enable the feature flag property and this should be good to go.

**Pull request closed without merging**
