### PR TITLE
LPS-183301 | Test Fix | Master

### PR DESCRIPTION
**Pull request by victorhcunha**
[LPS-183301](https://issues.liferay.com/browse/LPS-183301)

### CODE REVIEW

**Comment by victorhcunha** [comment]
ci:test:sf

**Comment by patriciajeanperez** [comment]
ci:forward

**Comment by victorhcunha** [comment]
Resending with signed commits

**Comment by victorhcunha** [comment]
ci:forward

**Comment by patriciajeanperez** [comment]
ci:forward

**Comment by patriciajeanperez** [comment]
ci:forward

**Pull request closed without merging**
