### PR TITLE
LPS-178249 | Test Fix | Master

### PR DESCRIPTION
**Pull request by victorhcunha**
[LPS-178249](https://issues.liferay.com/browse/LPS-178249)

### CODE REVIEW

**Comment by victorhcunha** [comment]
ci:test:sf

**Comment by victorhcunha** [comment]
ci:test:workflow-metrics

**Comment by victorhcunha** [comment]
The tests [DeletingSLAReflectInProgressInstances](https://testray.liferay.com/home/-/testray/case_results/2306746360?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayCaseName%3DDeletingSLAReflectInProgressInstances%26testrayBuildId%3D2306737618%26testrayRunId%3D2306744708%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc) and [DeletingSLANotReflectCompletedInstances](https://testray.liferay.com/home/-/testray/case_results/2306746327?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayCaseName%3DDeletingSLANotReflectCompletedInstances%26testrayBuildId%3D2306737618%26testrayRunId%3D2306744708%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc) have passed on ci

**Comment by patriciajeanperez** [comment]
ci:forward

**Pull request closed without merging**
