### PR TITLE
LPS-190765 | Test Fix | Master

### PR DESCRIPTION
**Pull request by alanafergs**
https://liferay.atlassian.net/browse/LPS-190765

### CODE REVIEW

**Comment by alanafergs** [comment]
ci:test:sf

**Comment by patriciajeanperez** [comment]
@alanafergs is this meant to fix LPS-190765?

**Comment by alanafergs** [comment]
> @alanafergs is this meant to fix LPS-190765?

Hey @patriciajeanperez It wouldn't exactly be to fix it, but rather to remove a line that was commented out in the code that shouldn't be.

**Comment by patriciajeanperez** [comment]
@alanafergs we should be using a different ticket then if this is not intended to fix what is described in the LPS

**Comment by timpak** [comment]
@alanafergs can you create a new ticket to fix this like @patriciajeanperez suggested? It makes it easier to track work and understand what you're doing. 

@patriciajeanperez since the issue was caused in LPS-190765, should the fix be committed under that ticket or the new one?

**Comment by alanafergs** [comment]
@timpak I can do it now, sorry for delay! 
cc: @patriciajeanperez

**Pull request closed without merging**
