### PR TITLE
LPS-176847, LPS-176851, LPS-176852, LPS-176844, LPS-177428, LPS-176845, LPS-176843, LPS-176850, LPS-176842 | Test Automation | Master

### PR DESCRIPTION
**Pull request by victorhcunha**
- [LPS-176847](https://issues.liferay.com/browse/LPS-176847) CanManageFormulaFieldWithCustomAction
- [LPS-176851](https://issues.liferay.com/browse/LPS-176851) CanMappedFormulaFieldOnPages
- [LPS-176852](https://issues.liferay.com/browse/LPS-176852) CanSystemAndCustomObjectRelatedWithFormulaField
- [LPS-176844](https://issues.liferay.com/browse/LPS-176844) ObjectFields#CanManageFormulaFieldWithLayout
- [LPS-177428](https://issues.liferay.com/browse/LPS-177428) ObjectFields#CanManageFormulaFieldWithView
- [LPS-176845](https://issues.liferay.com/browse/LPS-176845) FormulaFieldIsNotSearchable
- [LPS-176843](https://issues.liferay.com/browse/LPS-176843) CanEditFormulaFieldOnSystemObject
- [LPS-176842](https://issues.liferay.com/browse/LPS-176842) CanEditFormulaFieldOnCustomObject
- [LPS-176850](https://issues.liferay.com/browse/LPS-176850) CanFormulaFieldBeUsedWithUserNotification

Using macro/path from https://github.com/liferay-bpm-qa/liferay-portal/pull/552
Using macro/path from https://github.com/liferay-bpm-qa/liferay-portal/pull/546

Merged from https://github.com/liferay-bpm-qa/liferay-portal/pull/569
Merged (and adapted) from https://github.com/liferay-bpm-qa/liferay-portal/pull/549
Merged from https://github.com/liferay-bpm-qa/liferay-portal/pull/546
Merged from https://github.com/liferay-bpm-qa/liferay-portal/pull/550
Merged from https://github.com/liferay-bpm-qa/liferay-portal/pull/563

### CODE REVIEW

**Comment by victorhcunha** [comment]
ci:test:sf

**Comment by andreefarias** [comment]
So many tests separate related to Formula Field. I'll merge them all and send you a unique PR. Thanks!

**Comment by andreefarias** [comment]
Good job merging these PRs @victorhcunha. It's clean and organized. Thanks!

I will review this PR now.

**Comment by andreefarias** [comment]
ci:close

**Pull request closed without merging**
