### PR TITLE
LPS-184364 | Test Fix | Master

### PR DESCRIPTION
**Pull request by davisaints**
**JIRA Ticket: [LPS-184364](https://issues.liferay.com/browse/LPS-184364)**

### CODE REVIEW

**Comment by davisaints** [comment]
ci:test:sf

**Comment by davisaints** [comment]
ci:test:calendar

**Comment by davisaints** [comment]
ci:reevaluate:1377401_11398

**Comment by patriciajeanperez** [comment]
ci:test:calendar

**Comment by patriciajeanperez** [comment]
ci:forward

**Pull request closed without merging**
