### PR TITLE
LPS-146030 | Object Actions API | Master

### PR DESCRIPTION
**Pull request by andreefarias**
Ticket: [LPS-146030](https://liferay.atlassian.net/browse/LPS-146030)

### CODE REVIEW

**Comment by andreefarias** [comment]
ci:test:sf

**Comment by andreefarias** [comment]
ci:test:object

**Comment by andreefarias** [comment]
Add the externalReferenceCode for object definitions is optional. Failures not related.

**Review by timpak — APPROVED** [review]
LGTM! I'm going to assume you tested all of the curls, @andreefarias.

+666 lines of code 😈

**Comment by timpak** [comment]
ci:forward

**Pull request closed without merging**
