### PR TITLE
LPS-195550 | Test Fix | Master

### PR DESCRIPTION
**Pull request by victorhcunha**
[LPS-195550](https://liferay.atlassian.net/browse/LPS-195550)

### CODE REVIEW

**Comment by victorhcunha** [comment]
ci:test:sf

**Comment by patriciajeanperez** [comment]
@victorhcunha can we update the JIRA ticket to attach the LPS that caused this change?

**Comment by andreefarias** [comment]
LGTM! 🎉

**Comment by andreefarias** [comment]
ci:forward

**Comment by victorhcunha** [comment]
ci:forward

**Pull request closed without merging**
