### PR TITLE
LPS-171632

### PR DESCRIPTION
**Pull request by Natanaelbenvindo**
https://issues.liferay.com/browse/LPS-171632

### CODE REVIEW

**Comment by Natanaelbenvindo** [comment]
ci:test:sf

**Comment by andreefarias** [comment]
ci:test:sf

**Comment by andreefarias** [comment]
ci:close

**Comment by andreefarias** [comment]
Hey @Natanaelbenvindo,

I sent a new PR with your commit here: https://github.com/liferay-bpm-qa/liferay-portal/pull/275

**Pull request closed without merging**
