### PR TITLE
LPS-181202 | Master

### PR DESCRIPTION
**Pull request by davisaints**
**JIRA Ticket: [LPS-181476](https://issues.liferay.com/browse/LPS-181476)**

### CODE REVIEW

**Comment by davisaints** [comment]
ci:test:sf

**Comment by andreefarias** [comment]
ci:forward

**Comment by andreefarias** [comment]
Hey @davisaints, I updated the priority for this ticket: LPS-181204. Could update it, please?

**Comment by davisaints** [comment]
ci:test:sf

**Comment by andreefarias** [comment]
ci:forward

**Pull request closed without merging**
