### PR TITLE
LPS-183256 | Test Fix | Master

### PR DESCRIPTION
**Pull request by JerryAdrianoo**
**Ticket Jira :**

- [LPS-183256](https://issues.liferay.com/browse/LPS-183256)

### CODE REVIEW

**Comment by JerryAdrianoo** [comment]
ci:test:sf

**Comment by Luizcarlosqueiroz** [comment]
Hey @JerryAdrianoo ! Were you able to check that, by changing this macro, the other tests that uses that path are not failing too?

**Comment by JerryAdrianoo** [comment]
> Hey @JerryAdrianoo ! Were you able to check that, by changing this macro, the other tests that uses that path are not failing too?

Yeah, I saw it! They aren't broken with this alteration.

**Review by Luizcarlosqueiroz — APPROVED** [review]
LGTM! :tada:

**Comment by patriciajeanperez** [comment]
ci:test:data-engine

**Comment by patriciajeanperez** [comment]
ci:forward

**Pull request closed without merging**
