### PR TITLE
LPS-174662 | master

### PR DESCRIPTION
**Pull request by epark18**
https://issues.liferay.com/browse/LPS-174662

### CODE REVIEW

**Comment by epark18** [comment]
ci:test:sf

**Comment by epark18** [comment]
ci:test:sf

**Comment by epark18** [comment]
ci:test:object

**Comment by epark18** [comment]
ci:test:object

**Comment by epark18** [comment]
Postgre failures are https://issues.liferay.com/browse/LPS-182163. 
Will need to investigate why edit is not happening on CI.

**Comment by epark18** [comment]
https://issues.liferay.com/browse/LPS-182201 is the reason for object entries test failing

**Comment by epark18** [comment]
ci:test:object

**Comment by epark18** [comment]
Upgrades tests all passing

**Review by timpak — APPROVED** [review]

**Comment by timpak** [comment]
ci:forward

**Pull request closed without merging**
