### PR TITLE
LPS-181066 | Test Fix | Master

### PR DESCRIPTION
**Pull request by victorhcunha**
[LPS-181066](https://issues.liferay.com/browse/LPS-181066)

### CODE REVIEW

**Comment by victorhcunha** [comment]
ci:test:sf

**Comment by victorhcunha** [comment]
ci:test:object

**Comment by victorhcunha** [comment]
[CanRelateManyOtherEntriesBothObjects](https://testray.liferay.com/home/-/testray/case_results/index?delta=200&p_p_state=normal&orderByCol=status_sortable&orderByType=asc&testrayBuildId=2263292827&testrayRunId=2263292895&testrayCaseName=CanRelateManyOtherEntriesBothObjects) and [CascadeDeletionManyToManyWillAllowDelete](https://testray.liferay.com/home/-/testray/case_results/index?delta=200&p_p_state=normal&orderByCol=status_sortable&orderByType=asc&testrayBuildId=2263292827&testrayRunId=2263292895&testrayCaseName=CascadeDeletionManyToManyWillAllowDelete) passed on ci:test:object

**Review by timpak — APPROVED** [review]

**Comment by timpak** [comment]
ci:forward

**Pull request closed without merging**
