### PR TITLE
LPS-160652 | master

### PR DESCRIPTION
**Pull request by liuxingye**
https://issues.liferay.com/browse/LPS-160652

### CODE REVIEW

**Comment by liuxingye** [comment]
ci:test:sf

**Comment by liuxingye** [comment]
ci:test:sf

**Comment by liuxingye** [comment]
ci:test:sf

**Comment by epark18** [comment]
ci:forward

**Comment by liuxingye** [comment]
ci:forward

**Comment by epark18** [comment]
See https://github.com/liferay-bpm-qa/liferay-portal/pull/320

**Pull request closed without merging**
