### PR TITLE
LPS-198400 | Test Fix | Master

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
**Ticket:** [LPS-198400](https://liferay.atlassian.net/browse/LPS-198400)

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
ci:test:sf

**Comment by Luizcarlosqueiroz** [comment]
ci:test:echo

**Comment by Luizcarlosqueiroz** [comment]
ci:test:data-engine

**Comment by patriciajeanperez** [comment]
ci:forward

**Pull request closed without merging**
