### PR TITLE
LPS-200259 | Master

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
**Tickets:** [LPS-200259](https://liferay.atlassian.net/browse/LPS-200259)

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
ci:test:sf

**Comment by timpak** [comment]
I'm going to let @patriciajeanperez look at this since I don't have enough context to understand if deleting the tests is the right approach.

**Comment by patriciajeanperez** [comment]
Hey @Luizcarlosqueiroz, have we confirmed that we are no longer going to fix [LPS-178002](https://liferay.atlassian.net/browse/LPS-178002)?

**Comment by Luizcarlosqueiroz** [comment]
Hey @patriciajeanperez ! I spoke to Samuel, he said that we are not expecting to prioritize it to be fixed.

**Comment by patriciajeanperez** [comment]
ci:forward

**Pull request closed without merging**
