### PR TITLE
LPS-166585, LPS-166587 | master

### PR DESCRIPTION
**Pull request by chaowang-123**
https://issues.liferay.com/browse/LPS-166585
https://issues.liferay.com/browse/LPS-166587

### CODE REVIEW

**Comment by chaowang-123** [comment]
ci:test:sf

**Comment by chaowang-123** [comment]
ci:test:sf

**Comment by evanilson-santana** [comment]
Hi, @chaowang-123 can you please fix the conflicts?

**Comment by evanilson-santana** [comment]
Hey @chaowang-123 I added the two tests in a new [PR](https://github.com/liferay-bpm-qa/liferay-portal/pull/235). I'll close it

**Pull request closed without merging**
