### PR TITLE
LPS-179774,LPS-187957 | Test Fix | Master

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
**Ticket:** [LPS-179774](https://liferay.atlassian.net/browse/LPS-179774) , [LPS-187957](https://liferay.atlassian.net/browse/LPS-187957)

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
ci:test:sf

**Comment by patriciajeanperez** [comment]
Hey @Luizcarlosqueiroz! While I think this approach is better, there is an issue that we need to look into. The failures seem consistent on CI even if it is not consistent manually. My suggestion would be to forward this but have one test that updates the title right after duplicating and to look into the issue further. It only started failing consistently pretty recently, so there is a change that caused this. Let me know what you think!

**Comment by Luizcarlosqueiroz** [comment]
Hey @patriciajeanperez ! I agree with you, it makes sense two cover these two ways of setting the name. I'll update this PR with a solution that covers both scenarios.

**Comment by patriciajeanperez** [comment]
@Luizcarlosqueiroz I'll forward this. Let's keep an eye on the test to see if it catches the issue. If not, we'll have to update it to catch the bug. Thanks!

**Comment by patriciajeanperez** [comment]
ci:forward

**Pull request closed without merging**
