### PR TITLE
Test Fix | LPS-194280

### PR DESCRIPTION
**Pull request by evanilson-santana**
https://liferay.atlassian.net/browse/LPS-194280

Testray subtask: https://testray.liferay.com/home/-/testray/subtasks/2411064957

Some tests that use the `mapFragment` macro are breaking because they are not able to map a field in the heading fragment. The test fails because it tries to edit a non-editable element, and that's because the heading must be inside a collection display, and they aren't. I'm adding the collection display and heading inside the collection display to all tests that use `mapFragment` macro.

### CODE REVIEW

**Comment by evanilson-santana** [comment]
ci:test:sf

**Comment by evanilson-santana** [comment]
ci:test:object

**Comment by victorhcunha** [comment]
This fix is no more necessary because the tests is now passing on ci

**Comment by victorhcunha** [comment]
ci:close

**Pull request closed without merging**
