### PR TITLE
LPS-199545 | Automation | master

### PR DESCRIPTION
**Pull request by victorhcunha**
[LPS-199545](https://liferay.atlassian.net/browse/LPS-199545)

### CODE REVIEW

**Comment by victorhcunha** [comment]
ci:test:sf

**Review by timpak — APPROVED** [review]
LGTM!

**Comment by timpak** [comment]
@victorhcunha can you resolve the merge conflict then forward this?

**Comment by victorhcunha** [comment]
ci:test:sf

**Comment by victorhcunha** [comment]
ci:open

**Comment by victorhcunha** [comment]
ci:reopen

**Comment by victorhcunha** [comment]
ci:forward

**Pull request closed without merging**
