### PR TITLE
LPS-175982 | Test Fix | Master

### PR DESCRIPTION
**Pull request by victorhcunha**
Ticket:
https://issues.liferay.com/browse/LPS-175982

### CODE REVIEW

**Comment by victorhcunha** [comment]
ci:test:sf

**Comment by victorhcunha** [comment]
replaceFirst() -> replace the first occurrence of a substring

trim() -> remove the space present before and after a string

 

Old Code

 StringUtil.replaceFirst(${endDateTime}, " ", "");
Results

" 8:00 AM" -> "8:00 AM" 

" 9:00 AM" -> "9:00 AM" 

"10:00 AM" -> "10:00AM" 

"11:00 AM" -> "11:00AM" 

 

New Code

StringUtil.trim(${endDateTime});
Results

" 8:00 AM" -> "8:00 AM" 

" 9:00 AM" -> "9:00 AM" 

"10:00 AM" -> "10:00 AM" 

"11:00 AM" -> "11:00 AM"

**Comment by epark18** [comment]
ci:test:workflow

**Comment by epark18** [comment]
ci:forward

**Pull request closed without merging**
