### PR TITLE
LPS-197854 | master

### PR DESCRIPTION
**Pull request by davisaints**
JIRA Ticket: [LPS-197854](https://liferay.atlassian.net/browse/LPS-197854), [LPS-197249](https://liferay.atlassian.net/browse/LPS-197249)

## Root cause of failure:
Due to [this refactoring](https://github.com/liferay-echo/liferay-portal/pull/13697/commits/c8341959911bde71f57bc6ace0933ecbeaf2686f), the panel does not open when viewing the information. We need to open it to view the image field.

## Solution: 
I am opening the panel before asserting the image field

### CODE REVIEW

**Comment by patriciajeanperez** [comment]
@davisaints Thanks! Since you are touching a macro that belongs to a different team, would you be able to update them on this change that you are making?

**Comment by davisaints** [comment]
> @davisaints Thanks! Since you are touching a macro that belongs to a different team, would you be able to update them on this change that you are making?

The team has already been fixed. I'm just adding the parameters in the test

**Comment by davisaints** [comment]
ci:forward

**Comment by davisaints** [comment]
ci:stop

**Comment by davisaints** [comment]
ci:forward:force

**Comment by davisaints** [comment]
> @davisaints Thanks! Since you are touching a macro that belongs to a different team, would you be able to update them on this change that you are making?

The team has already fixed the macro. I just added a necessary parameter that they added in the test. Than you for the review!

cc/ @patriciajeanperez

**Pull request closed without merging**
