### PR TITLE
LPS-185032 | Test Improvement for coverage

### PR DESCRIPTION
**Pull request by JhossephG**
[LPS-185032](https://issues.liferay.com/browse/LPS-185032)

### CODE REVIEW

**Comment by JhossephG** [comment]
ci:test:stop

**Comment by JhossephG** [comment]
ci:test:sf

**Comment by timpak** [comment]
@JhossephG is this ready for review

**Comment by JhossephG** [comment]
Yes @timpak, t's ready

**Comment by timpak** [comment]
@JhossephG I'm really sorry, I put the wrong test on the ticket.

We should use a different test, because all we need to do is publish the object after the action is created. No need to create a new action here. Can you use CanCreateEntryWithActions for this? Just move the publish step after the action is added. No need to create a separate task, just add it at the end of the task that adds the action.

**Comment by JhossephG** [comment]
ci:test:sf

**Review by timpak — APPROVED** [review]

**Comment by timpak** [comment]
ci:forward

**Comment by timpak** [comment]
ci:forward

**Pull request closed without merging**
