### PR TITLE
LPS-196433 | master

### PR DESCRIPTION
**Pull request by davisaints**
**JIRA Ticket: [LPS-196433](https://liferay.atlassian.net/browse/LPS-196433)**

## Root cause of failure:
[This](https://github.com/liferay-echo/liferay-portal/pull/13610/commits/335de0aa8b9aa7d52a68e3d419f7702bdeb865d2) is the root cause, I didn't investigate what it's doing, but I believe it's a refactoring or something like that
## Solution:
I just updated the paths

### CODE REVIEW

**Comment by davisaints** [comment]
ci:test:workflow

**Comment by davisaints** [comment]
ci:stop

**Comment by davisaints** [comment]
ci:test:workflow

**Comment by davisaints** [comment]
No related failures! @patriciajeanperez

**Comment by patriciajeanperez** [comment]
ci:forward

**Pull request closed without merging**
