### PR TITLE
LPS-186336 | Master

### PR DESCRIPTION
**Pull request by davisaints**
**JIRA Ticket: [LPS-186336](https://liferay.atlassian.net/browse/LPS-186336)**

### Description:

Since LPS-186021 has been resolved, I am removing the workaround for it.

### CODE REVIEW

**Comment by davisaints** [comment]
ci:test:sf

**Comment by davisaints** [comment]
ci:test:workflow-metrics

**Comment by davisaints** [comment]
ci:test

**Comment by davisaints** [comment]
ci:test:workflow

**Comment by davisaints** [comment]
ci:stop

**Comment by davisaints** [comment]
ci:test:workflow-metrics

**Comment by davisaints** [comment]
No related failures! @patriciajeanperez

**Comment by patriciajeanperez** [comment]
ci:forward

**Comment by davisaints** [comment]
ci:stop

**Comment by davisaints** [comment]
ci:forward

**Pull request closed without merging**
