### PR TITLE
LPS-175693 | Test Fix | Master

### PR DESCRIPTION
**Pull request by JhossephG**
https://issues.liferay.com/browse/LPS-175693

### CODE REVIEW

**Comment by JhossephG** [comment]
ci:test:sf

**Comment by andreefarias** [comment]
Good job, @JhossephG! Don't forget to add the `index.html` on the ticket.

**Comment by andreefarias** [comment]
ci:forward

**Comment by JhossephG** [comment]
The attachments on Jira wasn't working yesterday

**Pull request closed without merging**
