### PR TITLE
LPS-185016 | Refactor | Master

### PR DESCRIPTION
**Pull request by victorhcunha**
[LPS-185016](https://issues.liferay.com/browse/LPS-185016)

### CODE REVIEW

**Comment by victorhcunha** [comment]
ci:test:sf

**Comment by patriciajeanperez** [comment]
ci:test:workflow

**Comment by patriciajeanperez** [comment]
ci:test:data-engine

**Comment by victorhcunha** [comment]
[CPDynamicdatalists#AddFormTemplate](https://testray.liferay.com/home/-/testray/case_results/2318715571?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayCaseName%3DAddFormTemplate%26testrayBuildId%3D2318692274%26testrayRunId%3D2318714307%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)
[PGDynamicdatalists#AddFormTemplate](https://testray.liferay.com/home/-/testray/case_results/2318715547?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayCaseName%3DAddFormTemplate%26testrayBuildId%3D2318692274%26testrayRunId%3D2318714307%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)
[DynamicdatalistsUsecase#FormTemplateUniqueField](https://testray.liferay.com/home/-/testray/case_results/2318715289?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayCaseName%3DFormTemplateUniqueField%26testrayBuildId%3D2318692274%26testrayRunId%3D2318714307%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)
[DynamicdatalistsUsecase#TemplateAddDeletedField](https://testray.liferay.com/home/-/testray/case_results/2318715292?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayCaseName%3DTemplateAddDeletedField%26testrayBuildId%3D2318692274%26testrayRunId%3D2318714307%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)

**Comment by victorhcunha** [comment]
ci:test:kaleo-forms

**Comment by patriciajeanperez** [comment]
ci:forward

**Pull request closed without merging**
