### PR TITLE
LPS-175182 | Test Automation | Master

### PR DESCRIPTION
**Pull request by davisaints**
**JIRA Ticket:** [LPS-175182](https://issues.liferay.com/browse/LPS-175182)

### CODE REVIEW

**Comment by davisaints** [comment]
ci:test:sf

**Comment by epark18** [comment]
ci:test:object

**Comment by epark18** [comment]
ci:test:object

**Comment by davisaints** [comment]
There are no related failures.

@epark18

**Comment by epark18** [comment]
ci:forward

**Pull request closed without merging**
