### PR TITLE
LPS-173533 | Test Automation | Master

### PR DESCRIPTION
**Pull request by thaiscabrals**
[FormsSubmissions#CannotNavigateThroughThePagesOnPublicPagesWithEmptyRequiredField](https://issues.liferay.com/browse/LPS-173533)

### CODE REVIEW

**Comment by thaiscabrals** [comment]
ci:test:sf

**Comment by andreefarias** [comment]
Looks good to me! 🎉 
Thanks, @thaiscabrals!

**Comment by andreefarias** [comment]
ci:forward

**Comment by andreefarias** [comment]
ci:forward

**Comment by thaiscabrals** [comment]
ci:forward

**Comment by thaiscabrals** [comment]
ci:stop

**Review by andreefarias — APPROVED** [review]

**Comment by andreefarias** [comment]
ci:forward

**Comment by thaiscabrals** [comment]
ci:forward

**Comment by andreefarias** [comment]
ci:stop

**Comment by thaiscabrals** [comment]
ci:forward

**Comment by thaiscabrals** [comment]
ci:stop

**Comment by evanilson-santana** [comment]
ci:forward

**Comment by evanilson-santana** [comment]
ci:forward

**Comment by evanilson-santana** [comment]
ci:stop

**Pull request closed without merging**
