### PR TITLE
LPS-192648 - Fix Automation | Data Engine | Master

### PR DESCRIPTION
**Pull request by thaiscabrals**
Ticket: 

- [LPS-192648](https://liferay.atlassian.net/browse/LPS-192648)

Tests: 

- DEFieldsGroup#CanBeCreatedWithFieldsOnBuilder
- DEFieldsGroup#CanDuplicateOrDeleteFields
- DETextField#CanBeDuplicated
- DENumericField#CanBeDuplicated

### CODE REVIEW

**Comment by thaiscabrals** [comment]
ci:test:sf

**Comment by thaiscabrals** [comment]
When duplicating a Field, the save button is disabled quickly so the click does not find the button.
I added a `WaitforElementPresent` because of this delay.

**Comment by thaiscabrals** [comment]
ci:reopen

**Comment by patriciajeanperez** [comment]
@thaiscabrals hey Thais! I still want to know why only double click works on automation, but not manually. Did you find the root cause of these failures?

**Comment by thaiscabrals** [comment]
ci:test:sf

**Comment by patriciajeanperez** [comment]
ci:forward

**Pull request closed without merging**
