### PR TITLE
LPS-173939  | Test Fix | Master

### PR DESCRIPTION
**Pull request by davisaints**
* https://issues.liferay.com/browse/LPS-173939

### CODE REVIEW

**Comment by davisaints** [comment]
ci:test:sf

**Comment by evanilson-santana** [comment]
Start Review

**Comment by evanilson-santana** [comment]
Hey @davisaints Thanks a lot for the fix and great job with it.  I'd just like to remind you to always try to create commits with more elaborate messages. You can see an example on this [document](https://liferay.atlassian.net/wiki/spaces/DXPL/pages/2114356408/Test+Review+Guidelines). And also don't forget to put the attachment index of the test result.

**Comment by evanilson-santana** [comment]
ci:forward

**Comment by davisaints** [comment]
Thanks for the feedback, @evanilson-santana! I will consolidate them in the next works.

**Pull request closed without merging**
