### PR TITLE
LPS-193145 | Test Improvement | Rename

### PR DESCRIPTION
**Pull request by JhossephG**
[LPS-193145](https://liferay.atlassian.net/browse/LPS-193145)

### CODE REVIEW

**Comment by JhossephG** [comment]
ci:test:sf

**Review by timpak — CHANGES_REQUESTED** [review]
Hey @JhossephG can you do the following:
- Use the commit message `Rename`
   - It's simpler and explains what your changes are doing, we should have examples of this in our codebase
- Please include a link to the ticket in the description

**Comment by timpak** [comment]
@JhossephG there's a merge conflict, unfortunately. Can you resolve it and forward this?

**Comment by JhossephG** [comment]
Resolved @timpak

**Comment by JhossephG** [comment]
ci:forward

**Pull request closed without merging**
