### PR TITLE
Test Fix| LPS-193134 | Master

### PR DESCRIPTION
**Pull request by evanilson-santana**
https://liferay.atlassian.net/browse/LPS-193134

## Overall context

Recently the macro `ObjectAdmin.addObjectFieldViaUI` was [here](https://github.com/brianchandotcom/liferay-portal/pull/142449) with the addition of the step:

```
WaitForVisible(
			key_fieldLabel = ${fieldLabel},
			locator1 = "ObjectAdmin#VIEW_OBJECT_FIELD_LABEL");
```

This causes our test to fail, since before adding fields via the UI, many other fields are added via the API, causing the fields via the UI to be allocated on the last pages and not seen on the first page for the assert.

It is questionable whether this extra step would even be necessary since the [test](https://github.com/brianchandotcom/liferay-portal/pull/142449/commits/28bb673843efc59a0163e85f3e11ebc6c32234b7) added in PR with this modification passes in ci even without this wait (as you can see [here](https://testray.liferay.com/home/-/testray/case_results/2446703846?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2446701950%26testrayRunId%3D2446703820%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)).

To avoid another change in the macro I just changed the order in which the fields are added, making the test add them first via the UI and then via the API.

## Context about the changes 
The commit: `"Add new approach in importObject macro"` will be a new approach for the macro `importObject` where currently it just imports files from the dependencies directory, so with the `"var tempFileName = TestCase.getDownloadedTempFileName(fileNamePattern = "Object_${objectName}*.json");"` and `var tempFileDirectory = selenium.getOutputDirName();`  now the macro will also import temporary files.

### CODE REVIEW

**Comment by evanilson-santana** [comment]
ci:test:sf

**Comment by evanilson-santana** [comment]
ci:test:object-functional

**Comment by evanilson-santana** [comment]
This test won't pass because there is a bug around the test steps: [LPS-201978](https://liferay.atlassian.net/browse/LPS-201978). When it is resolved the test is back to pass.

**Comment by victorhcunha** [comment]
resent here #1315

**Pull request closed without merging**
