### PR TITLE
LPS-183450 | Change File Location of oldValue Testcases

### PR DESCRIPTION
**Pull request by JhossephG**
[LPS-183450](https://issues.liferay.com/browse/LPS-183450)

### CODE REVIEW

**Comment by JhossephG** [comment]
ci:test:object

**Comment by timpak** [comment]
@JhossephG is this ready for review or are you still working on this

**Comment by JhossephG** [comment]
It's ready to you review, all the tests that I changed the location passed on the `ci:test:object` suite

**Review by timpak — CHANGES_REQUESTED** [review]
@JhossephG can you rebase your commit, there's a merge conflict.

Also, can you update your commit message? It should start with a present tense verb like:
`Extract Old Value tests into a separate testcase file`

**Comment by JhossephG** [comment]
ci:test:sf

**Comment by JhossephG** [comment]
It's ready @timpak

**Comment by JhossephG** [comment]
ci:test:sf

**Comment by JhossephG** [comment]
ci:test:sf

**Review by timpak — APPROVED** [review]
LGTM!

**Comment by timpak** [comment]
ci:forward

**Comment by timpak** [comment]
ci:forward

**Pull request closed without merging**
