### PR TITLE
LPS-191311 | Update object environments | Master

### PR DESCRIPTION
**Pull request by andreefarias**
Ticket: [LPS-191311](https://liferay.atlassian.net/browse/LPS-191311)

### CODE REVIEW

**Comment by andreefarias** [comment]
ci:test:sf

**Comment by andreefarias** [comment]
ci:test:sf

**Review by timpak — APPROVED** [review]

**Comment by timpak** [comment]
@andreefarias in the future, please use a more descriptive commit message like

`Remove Sybase from the Object environments test suite because it isn't supported`

**Comment by timpak** [comment]
ci:forward

**Pull request closed without merging**
