### PR TITLE
LPS-182611 | Test Fix | Master

### PR DESCRIPTION
**Pull request by JerryAdrianoo**
**Ticket Jira :**
- [LPS-182611](https://issues.liferay.com/browse/LPS-182611)

### CODE REVIEW

**Comment by JerryAdrianoo** [comment]
ci:test:sf

**Review by Luizcarlosqueiroz — CHANGES_REQUESTED** [review]
Hey @JerryAdrianoo !
This action `Click(locator1 = "UserBar#USER_AVATAR_ICON");` is already performed by UserBar.gotoDropdownItem(dropdownItem = "My Workflow Tasks");
I think the issue here is that, before clicking to open the User Menu, the pop-up from the Calendar Event Modal still open, and therefore poshi/web drive is 'losing focus' and not clicking properly. I would recommend an click to close that Event Modal and check if that solves the problem.

**Comment by Luizcarlosqueiroz** [comment]
Since this is a different approach to fix it, I'll close this PR, and feel free to re-open once you have updates.

**Comment by JerryAdrianoo** [comment]
ci:reopen

**Pull request closed without merging**
