### PR TITLE
LPS-162177 | Test Automation | master

### PR DESCRIPTION
**Pull request by epark18**
https://issues.liferay.com/browse/LPS-162177

### CODE REVIEW

**Comment by epark18** [comment]
ci:test:sf

**Comment by epark18** [comment]
@evanilson-santana if this looks good to you I think we can forward.

**Comment by evanilson-santana** [comment]
> @evanilson-santana if this looks good to you I think we can forward.

Okay, thanks

**Comment by evanilson-santana** [comment]
ci:forward

**Pull request closed without merging**
