### PR TITLE
LPS-196514 | master

### PR DESCRIPTION
**Pull request by davisaints**
**JIRA Ticket:** **[LPS-196514](https://liferay.atlassian.net/browse/LPS-196514)**

## Root cause of failure:
Single approver cannot be manipulated when the "Allow admins to publish and edit workflows" option is not enabled on a virtual instance. Also, the test was created in the wrong testcase file

## Solution:
Do not run the tests on a virtual instance

### CODE REVIEW

**Comment by davisaints** [comment]
ci:test:workflow

**Comment by davisaints** [comment]
ci:stop

**Comment by davisaints** [comment]
ci:test:workflow

**Comment by davisaints** [comment]
The test passed! @patriciajeanperez

**Comment by patriciajeanperez** [comment]
ci:forward

**Pull request closed without merging**
