### PR TITLE
LPS-183407 | Test Fix | Master

### PR DESCRIPTION
**Pull request by JerryAdrianoo**
**Ticket Jira:**
- [LPS-183407](https://issues.liferay.com/browse/LPS-183407)

### CODE REVIEW

**Comment by JerryAdrianoo** [comment]
ci:test:sf

**Review by Luizcarlosqueiroz — APPROVED** [review]
LGTM!

**Comment by patriciajeanperez** [comment]
Hey @JerryAdrianoo @Luizcarlosqueiroz, should we just assert the correct value expected by CI? In this case, 7AM to 8AM? Our test on CI and the one on your local will not have the same values since our test has this property set: `company.default.time.zone=America/Los_Angeles`

**Comment by JerryAdrianoo** [comment]
> Hey @JerryAdrianoo @Luizcarlosqueiroz, should we just assert the correct value expected by CI? In this case, 7AM to 8AM? Our test on CI and the one on your local will not have the same values since our test has this property set: `company.default.time.zone=America/Los_Angeles`

In this case, we need left failing on local and passed on CI ?

**Comment by patriciajeanperez** [comment]
@JerryAdrianoo yea, so if you set that property in your `portal-ext.properties` file, your test should pass locally.

**Comment by JerryAdrianoo** [comment]
> @JerryAdrianoo yea, so if you set that property in your `portal-ext.properties` file, your test should pass locally.

Cool !! I didn't know. I tested and works. Thanks

**Comment by patriciajeanperez** [comment]
ci:forward

**Pull request closed without merging**
