### PR TITLE
LPS-171875 | Test fix | Master

### PR DESCRIPTION
**Pull request by alanafergs**
https://issues.liferay.com/browse/LPS-171875

### CODE REVIEW

**Comment by alanafergs** [comment]
ci:test:sf

**Comment by epark18** [comment]
@alanafergs Hey this SF failed because of your commit message. _=LPS-171875_ Could you change it so it doesn't contain the "="? Thank you!

**Comment by alanafergs** [comment]
ci:test:sf

**Comment by alanafergs** [comment]
ci:forward

**Pull request closed without merging**
