### PR TITLE
LPS-176375 | Test Fix | Master

### PR DESCRIPTION
**Pull request by JerryAdrianoo**
https://issues.liferay.com/browse/LPS-176375

### CODE REVIEW

**Comment by JerryAdrianoo** [comment]
ci:test:sf

**Comment by epark18** [comment]
See https://github.com/liferay-bpm-qa/liferay-portal/pull/491

**Comment by epark18** [comment]
Hey @JerryAdrianoo Thanks for your work on this. I had assigned this ticket to myself earlier since I forwarded something that broke the tests by mistake.

**Comment by JerryAdrianoo** [comment]
> Hey @JerryAdrianoo Thanks for your work on this. I had assigned this ticket to myself earlier since I forwarded something that broke the tests by mistake. We will use the newer one because there was a second test that needed to be fixed.

Hi, Erik. 
Thanks for the info. I didn't see it. Our solutions look similar hahaha. Cool.

**Pull request closed without merging**
