### PR TITLE
LPS-178933 | Test Fix | Master

### PR DESCRIPTION
**Pull request by victorhcunha**
[LPS-178933](https://issues.liferay.com/browse/LPS-178933)

### CODE REVIEW

**Comment by victorhcunha** [comment]
ci:test:sf

**Comment by andreefarias** [comment]
ci:forward

**Comment by andreefarias** [comment]
ci:forward:force

**Comment by andreefarias** [comment]
ci:stop

**Comment by andreefarias** [comment]
ci:forward

**Comment by andreefarias** [comment]
ci:stop

**Comment by andreefarias** [comment]
ci:forward:force

**Comment by andreefarias** [comment]
ci:stop

**Pull request closed without merging**
