### PR TITLE
LPS-192019 | Master

### PR DESCRIPTION
**Pull request by alanafergs**
https://liferay.atlassian.net/browse/LPS-192019

### CODE REVIEW

**Comment by alanafergs** [comment]
ci:test:sf

**Review by patriciajeanperez — CHANGES_REQUESTED** [review]
@alanafergs Hey Alana! I have a few suggestions for this PR:

1. Make use of macros that will make the tests faster like using JSON and navigating via URLs
2. Are all the steps in the bug ticket covered already? It seems like the original bug was reproduced when selecting an image again
3. Please write all future tests and this one using BDD (Given, When, Then)

Thank you, @alanafergs! Let me know if you have any questions.

**Comment by alanafergs** [comment]
ci:test:sf

**Comment by alanafergs** [comment]
ci:test:sf

**Comment by patriciajeanperez** [comment]
ci:forward

**Comment by patriciajeanperez** [comment]
ci:forward

**Comment by patriciajeanperez** [comment]
ci:forward

**Comment by patriciajeanperez** [comment]
ci:forward

**Comment by patriciajeanperez** [comment]
ci:forward:force

**Pull request closed without merging**
