### PR TITLE
LPS-173671 | Test Fix | Master

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
**Ticket:**
[LPS-173671](https://issues.liferay.com/browse/LPS-173671)

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
ci:test:sf

**Comment by patriciajeanperez** [comment]
@Luizcarlosqueiroz Thank you, Luiz! Did we check to see if the other tests that use DDLRecord.populateFieldLinkToPage are still working?

**Comment by Luizcarlosqueiroz** [comment]
Hey @patriciajeanperez ! Only three tests were using this macro:
- One is being fixed by this PR
- Another was ignored, but the scenario is no longer reproducible, since the current modal does not leaves breadcrumbs (LPS-67478), so I removed it
- The last is also ignored, and it's failing prior to the execution of this macro. As I couldn't find a ticket already created, I created another one to work on it LPS-183565.

**Comment by patriciajeanperez** [comment]
Looks great @Luizcarlosqueiroz. See additional changes in https://github.com/liferay-bpm-qa/liferay-portal/pull/779

**Pull request closed without merging**
