### PR TITLE
LPS-183319 | Test Fix | Master

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
**Ticket:**
[LPS-183319](https://issues.liferay.com/browse/LPS-183319):
Refactor tests related to Process Builder Timers

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
ci:test:sf

**Comment by Luizcarlosqueiroz** [comment]
Tested using: [ci:test:default](https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2288336669)

**Comment by patriciajeanperez** [comment]
Thank you for refactoring and making these tests run again, @Luizcarlosqueiroz!

**Comment by patriciajeanperez** [comment]
ci:forward

**Pull request closed without merging**
