### PR TITLE
LPS-189802 | Bot to trigger the ci:test:sf |Master

### PR DESCRIPTION
**Pull request by andreefarias**
Ticket: [LPS-189802](https://liferay.atlassian.net/browse/LPS-189802)

Adding the bot to trigger automatically the **ci:test:sf** on **liferay-bpm-qa**

### CODE REVIEW

**Comment by andreefarias** [comment]
ci:test:sf

**Comment by timpak** [comment]
@andreefarias why are we enabling automatically running SF here? We should be running SF locally before submitting PRs.

**Comment by andreefarias** [comment]
We ran the sf locally and after we used ci:test:sf on PR. So, I thought in automate this step, but it's not necessary.

cc: @timpak

**Comment by timpak** [comment]
I'm going to close this PR and the ticket since we don't need this.

**Pull request closed without merging**
