### PR TITLE
LPS-186079 | Test fix | Master

### PR DESCRIPTION
**Pull request by andreefarias**
Ticket: [LPS-186079](https://issues.liferay.com/browse/LPS-186079)
Failed only on CI: [testray](https://testray.liferay.com/home/-/testray/cases/1869061063)

I took the opportunity to refactor the names of the tasks, remove the steps unnecessary, and organized them.

### CODE REVIEW

**Comment by andreefarias** [comment]
ci:test:sf

**Comment by timpak** [comment]
Hey @andreefarias, can you split this into separate commits and use clearer messages? It's unclear what you're fixing vs what's being refactored/re-organized. It's good practice to use small, logical changes with clear messages so it's easy to understand the purpose of each commit. If you can't clearly describe what your changes are doing with a simple sentence/phrase, you probably need to split it up. If needed, I can do a call with you to explain what I mean with examples.

**Comment by andreefarias** [comment]
Hi @timpak, I split the commits into fixes and tasks.

The failure happen only on CI because the property not is called via API, so I changed some macros of position and used a logic more consistent (without losing the real goal).

The other commit has related tasks with BDD steps.

Is it good for you?

**Comment by timpak** [comment]
See https://github.com/liferay-bpm-qa/liferay-portal/pull/911

**Pull request closed without merging**
