### PR TITLE
LPS-185900 LPS-186239 | Workaround for tests

### PR DESCRIPTION
**Pull request by victorhcunha**
[LPS-186239](https://issues.liferay.com/browse/LPS-186239) Add workaround for tests

### CODE REVIEW

**Comment by victorhcunha** [comment]
ci:test:sf

**Comment by patriciajeanperez** [comment]
Hey @victorhcunha! Can we update the test to do a workaround for now? I saw that the workaround for the bug is to refresh so maybe we can update the test to refresh for now so at least we don't lose test coverage for this. Just make sure you add a comment to the test that it is a workaround so when the bug is fixed, we know in the future to remove it. Thanks!

cc @Luizcarlosqueiroz

**Comment by victorhcunha** [comment]
ci:test:workflow-metrics

**Comment by victorhcunha** [comment]
Waiting for ci:test:workflow-metrics to see if workaround will be necessary in more steps

**Comment by victorhcunha** [comment]
Passed tests after workaround:

- [LocalFile.WorkflowMetrics#AddSLAForTotalProcessResolution](https://testray.liferay.com/home/-/testray/case_results/2326951558?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2326951390%26testrayRunId%3D2326951427%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc) ✅
- [LocalFile.WorkflowMetrics#AddSLAtoSingleApprover](https://testray.liferay.com/home/-/testray/case_results/2326951496?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2326951390%26testrayRunId%3D2326951427%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc) ✅
- [LocalFile.WorkflowMetrics#SeeListOfReports](https://testray.liferay.com/home/-/testray/case_results/2326952065?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2326951390%26testrayRunId%3D2326951427%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc) ✅
-  [LocalFile.WorkflowMetrics#VerifyFilterTopStepPerformance](https://testray.liferay.com/home/-/testray/case_results/2326952453?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2326951390%26testrayRunId%3D2326951427%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc) ✅
- [LocalFile.WorkflowMetrics#ViewCompletedItems](https://testray.liferay.com/home/-/testray/case_results/2326952153?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2326951390%26testrayRunId%3D2326951427%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc) ✅
- [LocalFile.WorkflowMetrics#ViewPendingItems](https://testray.liferay.com/home/-/testray/case_results/2326952066?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2326951390%26testrayRunId%3D2326951427%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc) ✅
- [LocalFile.WorkflowMetricsSLA#BlockedSLACanBeFixed](https://testray.liferay.com/home/-/testray/case_results/2326952320?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2326951390%26testrayRunId%3D2326951427%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc) ✅
- [LocalFile.WorkflowMetricsSLA#UpdatingSLARecalculateTimeInProgressInstances](https://testray.liferay.com/home/-/testray/case_results/2326952390?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2326951390%26testrayRunId%3D2326951427%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc) ✅


 [LocalFile.WorkflowMetrics#UpdateandDeleteSLA] X

**Comment by victorhcunha** [comment]
Hi @patriciajeanperez !
It's really the best idea keep the tests running using the workaround
The changes were made and the tests passed on ci

**Comment by victorhcunha** [comment]
ci:tests:sf

**Comment by victorhcunha** [comment]
ci:test:sf

**Comment by patriciajeanperez** [comment]
Hey @victorhcunha, can we do an if/else instead? or if the issue is consistent, just add a refresh step without any if/else or while statement. Just wanted to shorten the runtime of these tests as much as possible.

**Comment by victorhcunha** [comment]
Hi, @patriciajeanperez !
The while is to ensure that the tests will run correctly.
By the consistency of the issue, only one round is needed to execute, but if this is not the case at some point, the test will continue to work anyway.
I will resend without the `while ` .

**Comment by victorhcunha** [comment]
ci:test:workflow-metrics

**Comment by victorhcunha** [comment]
Tests after workaround (without while):

[LocalFile.WorkflowMetrics#AddSLAForTotalProcessResolution](https://testray.liferay.com/home/-/testray/case_results/2341075690?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayCaseName%3DAddSLAForTotalProcessResolution%26testrayBuildId%3D2341075017%26testrayRunId%3D2341075152%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc) white_check_mark
[LocalFile.WorkflowMetrics#AddSLAtoSingleApprover](https://testray.liferay.com/home/-/testray/case_results/2341075568?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayCaseName%3DAddSLAtoSingleApprover%26testrayBuildId%3D2341075017%26testrayRunId%3D2341075152%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc) white_check_mark
[LocalFile.WorkflowMetrics#SeeListOfReports](https://testray.liferay.com/home/-/testray/case_results/2341075642?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayCaseName%3DSeeListOfReports%26testrayBuildId%3D2341075017%26testrayRunId%3D2341075152%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc) white_check_mark
[LocalFile.WorkflowMetrics#VerifyFilterTopStepPerformance](https://testray.liferay.com/home/-/testray/case_results/2341076124?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayCaseName%3DVerifyFilterTopStepPerformance%26testrayBuildId%3D2341075017%26testrayRunId%3D2341075152%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc) white_check_mark
[LocalFile.WorkflowMetrics#ViewCompletedItems](https://testray.liferay.com/home/-/testray/case_results/2341075978?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayCaseName%3DViewCompletedItems%26testrayBuildId%3D2341075017%26testrayRunId%3D2341075152%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc) white_check_mark
[LocalFile.WorkflowMetrics#ViewPendingItems](https://testray.liferay.com/home/-/testray/case_results/2341076156?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayCaseName%3DViewPendingItems%26testrayBuildId%3D2341075017%26testrayRunId%3D2341075152%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc) white_check_mark


[LocalFile.WorkflowMetricsSLA#BlockedSLACanBeFixed]() white_check_mark
[LocalFile.WorkflowMetricsSLA#UpdatingSLARecalculateTimeInProgressInstances]() white_check_mark
[LocalFile.WorkflowMetrics#UpdateandDeleteSLA]() white_check_mark - another Testray Build

**Comment by patriciajeanperez** [comment]
ci:test:sf

**Comment by patriciajeanperez** [comment]
Thank you, @victorhcunha!

**Comment by patriciajeanperez** [comment]
ci:forward

**Pull request closed without merging**
