### PR TITLE
LPS-202741 | Test Fix | Master

### PR DESCRIPTION
**Pull request by victorhcunha**
[LPS-202741](https://liferay.atlassian.net/browse/LPS-202741)

Changes:
- variable in the GO_TO_FOLDER path is fixed
- path OBJECT_IN_LEFT_SIDEBAR_KEBAB_MENU is created for the Poshi can use the kebab menu to move the object to the current folder
- the test `CanMoveObjectDefinitionToCurrentFolder` is fixed so that the steps are carried out correctly in the model builder (the previous steps were confusing because they were based on page view elements) and unnecessary steps were removed
- the path SELECT_OBJECT_IN_LEFT_SIDEBAR is updated to use the folder label and the change is applied to test `CanSearchForObjectDefinition` (the test passes)

This is the original ticket for automation: [LPS-195650](https://liferay.atlassian.net/browse/LPS-195650)

### CODE REVIEW

**Comment by victorhcunha** [comment]
ci:test:sf

**Comment by victorhcunha** [comment]
ci:test:sf

**Comment by timpak** [comment]
ci:forward

**Comment by victorhcunha** [comment]
ci:forward:force

**Comment by victorhcunha** [comment]
ci:forward:force

**Comment by victorhcunha** [comment]
ci:forward

**Comment by thaiscabrals** [comment]
ci:forward

**Comment by Luizcarlosqueiroz** [comment]
Hey @victorhcunha ! Maybe it's better to sent it directly to bchan repo.

**Comment by victorhcunha** [comment]
@thaiscabrals  @Luizcarlosqueiroz Thanks!
resent here #1332

**Pull request closed without merging**
