### PR TITLE
Test Fix path Object Portlet Header - LPS-166213 | master

### PR DESCRIPTION
**Pull request by Italo-gabriel**
https://issues.liferay.com/browse/LPS-166213

### CODE REVIEW

**Comment by evanilson-santana** [comment]
ci:forward

**Comment by evanilson-santana** [comment]
Hi @Italo-gabriel this commit needs to be linked from a LPS

**Comment by Italo-gabriel** [comment]
ci:test:sf

**Comment by andreefarias** [comment]
ci:forward

**Pull request closed without merging**
