### PR TITLE
LPS-181481| Test fix | Master

### PR DESCRIPTION
**Pull request by davicms**
[#CanSaveDirectlyFromUsersComputerOptionWithShowFilesDisable](https://issues.liferay.com/browse/LPS-181481)

### CODE REVIEW

**Comment by davicms** [comment]
ci:test:sf

**Review by Luizcarlosqueiroz — APPROVED** [review]
LGTM! :tada:

**Comment by epark18** [comment]
Good job @davicms Remember to attach test results on the ticket in the future. Thank you!

**Comment by epark18** [comment]
ci:forward

**Pull request closed without merging**
