### PR TITLE
[Test Fix] Investigate ObjectPermission Tests - LPS-169627

### PR DESCRIPTION
**Pull request by PedroBuarque**
https://issues.liferay.com/browse/LPS-169627

### CODE REVIEW

**Comment by PedroBuarque** [comment]
ci:test:sf

**Comment by thaiscabrals** [comment]
ci:stop

**Comment by thaiscabrals** [comment]
ci:test:sf

**Comment by thaiscabrals** [comment]
ci:test:relevant

**Comment by thaiscabrals** [comment]
ci:test:sf

**Comment by PedroBuarque** [comment]
ci:test:relevant

**Comment by thaiscabrals** [comment]
ci:test:sf

**Comment by thaiscabrals** [comment]
ci:forward

**Pull request closed without merging**
