### PR TITLE
LPS-194805 | Test fix | Master

### PR DESCRIPTION
**Pull request by Natanaelbenvindo**
[LPS-194805](https://liferay.atlassian.net/browse/LPS-194805) 
I added a refresh step

### CODE REVIEW

**Comment by Natanaelbenvindo** [comment]
ci:test:sf

**Comment by andreefarias** [comment]
ci:test:sf

**Comment by andreefarias** [comment]
LGTM! 🎉

**Comment by andreefarias** [comment]
ci:forward

**Pull request closed without merging**
