### PR TITLE
[Test Fix] LPS-169624 - Investigate ObjectCustomViews tests

### PR DESCRIPTION
**Pull request by PedroBuarque**
https://issues.liferay.com/browse/LPS-169624

### CODE REVIEW

**Comment by PedroBuarque** [comment]
ci:test:sf

**Comment by PedroBuarque** [comment]
ci:test:sf

**Review by rafaellajordao — CHANGES_REQUESTED** [review]
Hi Pedro! good job with the fix! :+1: 

Just one more thing, if the test is passing can you remove the Quarantine property please?

**Comment by PedroBuarque** [comment]
ci:test:sf

**Review by rafaellajordao — APPROVED** [review]
Good to Go! :)

**Comment by rafaellajordao** [comment]
ci:forward

**Pull request closed without merging**
