### PR TITLE
LPS-137958 | Test Refactor | Master

### PR DESCRIPTION
**Pull request by rebsilva**
Related Issue: https://issues.liferay.com/browse/LPS-137958

### CODE REVIEW

**Comment by rebsilva** [comment]
ci:test:sf

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
ci:test:object

**Comment by epark18** [comment]
ci:test:object

**Comment by epark18** [comment]
@evanilson-santana This looks good to me, but you can double check and forward.

**Comment by evanilson-santana** [comment]
Hey, @epark18 it looks good for me too. @rebsilva please, can you resolve these conflicts?

**Comment by timpak** [comment]
@rebsilva if you don't have bandwidth to work on this, let us know! @evanilson-santana if she's not free, can you assign this to one of the SDG guys? They should be familiar with fixing merge conflicts from their training I think.

**Comment by rebsilva** [comment]
@evanilson-santana @timpak @davisaints Thanks a lot for your help on this! I really appreciate it :purple_heart:

**Pull request closed without merging**
