### PR TITLE
LPS-201555 | Test Fix | master

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
**Ticket**: [LPS-201555](https://liferay.atlassian.net/browse/LPS-201555)

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
ci:test:sf

**Comment by patriciajeanperez** [comment]
Hey @Luizcarlosqueiroz, did you also run other tests that use these paths?

**Comment by Luizcarlosqueiroz** [comment]
Hey @patriciajeanperez !

- `NOTIFICATIONS_TYPE_DROPDOWN`
It's used in 4 macros, but only one of them actually uses this path (the others are set as conditionals with `isSet`). The test from this fix uses this macro, and I also ran another.
- `NOTIFICATION_TYPE_OPTIONS`
It's used in the same 4 macros, as well as in another test directly from testcase layer. This test is also passing (added the index at the ticket)

**Comment by patriciajeanperez** [comment]
Thank you, @Luizcarlosqueiroz!

**Comment by patriciajeanperez** [comment]
ci:forward

**Pull request closed without merging**
