### PR TITLE
LPS-193027 | Test fix | Master

### PR DESCRIPTION
**Pull request by mateussandes23**
https://liferay.atlassian.net/browse/LPS-193027

### CODE REVIEW

**Comment by mateussandes23** [comment]
ci:test:sf

**Comment by timpak** [comment]
This behavior looks weird. @mateussandes23 did you confirm with anyone that this is the intended behavior?

**Comment by mateussandes23** [comment]
Hey @timpak , I asked @andreefarias about this behaviour and he said that it was a change on frontend. I will open a thread to confirm the behavior.

**Comment by mateussandes23** [comment]
@timpak , I made as investigation for this behavior and it's bug. I posted on this [thread](https://liferay.slack.com/archives/C026UR5976G/p1692213125243639) and will open a ticket for it.

**Comment by andreefarias** [comment]
Hey @mateussandes23,

The bug related to this was fixed, see here.

I'll close this PR. Thanks!

**Pull request closed without merging**
