### PR TITLE
LPS-171335 | Test Fix | Master

### PR DESCRIPTION
**Pull request by victorhcunha**
[LPS-171335](https://issues.liferay.com/browse/LPS-171335)

### CODE REVIEW

**Comment by victorhcunha** [comment]
ci:test:sf

**Comment by patriciajeanperez** [comment]
Hi @victorhcunha! Thank you for this. It looks like the test was originally asserting the header that says `Review: Kaleo Forms Process`. Can you make sure the test will still do that after the fix?

**Comment by victorhcunha** [comment]
ci:test:sf

**Comment by victorhcunha** [comment]
ci:test:sf

**Comment by victorhcunha** [comment]
> Hi @victorhcunha! Thank you for this. It looks like the test was originally asserting the header that says `Review: Kaleo Forms Process`. Can you make sure the test will still do that after the fix?

Hi @patriciajeanperez ! I make some adjusts to still do that, can you review it?

**Comment by patriciajeanperez** [comment]
@victorhcunha perfect! Nice work using existing path too.

**Comment by patriciajeanperez** [comment]
ci:forward

**Pull request closed without merging**
