### PR TITLE
LPS-184074 | Refactor | Master

### PR DESCRIPTION
**Pull request by victorhcunha**
[LPS-184074](https://issues.liferay.com/browse/LPS-184074)

### CODE REVIEW

**Comment by victorhcunha** [comment]
The macro has the objective to access a specific month in the calendar.

In its old version, you had to go through the calendar until February 2016 and then continue until the specified month.
The test was too long and brought a range limit in which months before February 2016 could not be reached.

Now the macro goes to the desired year to only go through the months within that year to reach the specified, saving time and resources.

**Comment by victorhcunha** [comment]
ci:test:sf

**Comment by patriciajeanperez** [comment]
Thank you for this, @victorhcunha! Does this fix `CalendarScheduler.ViewCorrectNumberOfWeeksMonthView`? If so, can you include the html file in the ticket and also remove the test from quarantine?

**Comment by victorhcunha** [comment]
Hi @patriciajeanperez !
The fix for `CalendarScheduler.ViewCorrectNumberOfWeeksMonthView` is in #797 (already merged).
I keep the pr separated because the goal here is to improve test performance.

**Comment by patriciajeanperez** [comment]
gotcha, thanks for the reminder! @victorhcunha

**Comment by patriciajeanperez** [comment]
ci:forward

**Pull request closed without merging**
