### PR TITLE
LPS-193457 | Master

### PR DESCRIPTION
**Pull request by davisaints**
**JIRA Ticket:** [LPS-193457](https://liferay.atlassian.net/browse/LPS-193457)

## Root cause of this failure: 
Probably this [block](https://github.com/brianchandotcom/liferay-portal/pull/139100/files#diff-481111bbc337a79298ea0fa2a1c8ae815ad54ddf6b43fda3ee01ee5f615a0ec0R39-R55) of code is the root cause.

## Solution: 
I only replaced the 'id' attribute with 'name' so that the captcha field can be located.

### CODE REVIEW

**Comment by davisaints** [comment]
ci:test:sf

**Comment by patriciajeanperez** [comment]
@davisaints can you attach the passing html file of the test or two that uses this path? Thanks!

**Comment by davisaints** [comment]
Done! @patriciajeanperez

**Comment by davisaints** [comment]
Done! This path is only used by this test @patriciajeanperez

**Comment by patriciajeanperez** [comment]
ci:forward

**Comment by davisaints** [comment]
ci:forward

**Comment by davisaints** [comment]
ci:stop

**Comment by davisaints** [comment]
ci:forward:force

**Comment by davisaints** [comment]
ci:forward

**Pull request closed without merging**
