### PR TITLE
LPS-187948 | Test Fix | Master

### PR DESCRIPTION
**Pull request by victorhcunha**
[LPS-187948](https://liferay.atlassian.net/browse/LPS-187948)

### CODE REVIEW

**Comment by victorhcunha** [comment]
ci:test:sf

**Comment by victorhcunha** [comment]
Obs: that path is used only for one macro

**Comment by timpak** [comment]
Hey @victorhcunha did you test this fix with the affected tests? If so, you can forward this

**Comment by victorhcunha** [comment]
This fix affect only one test

**Comment by victorhcunha** [comment]
ci:foward

**Comment by timpak** [comment]
ci:forward

**Pull request closed without merging**
