### PR TITLE
LPS-185491 | Quarantine | Master

### PR DESCRIPTION
**Pull request by sirfabios**
https://issues.liferay.com/browse/LPS-185491

### CODE REVIEW

**Comment by sirfabios** [comment]
ci:test:sf

**Comment by timpak** [comment]
@sirfabios please do the following:
- Assign the ticket to yourself and move it into `In Progress`
- Leave an explanation why we're quarantining the test on the ticket
   - Without context, it's very difficult for other people to understand why we're quarantining this 
- Create a ticket to remove the test from quarantine and link it to this ticket
   - We want to remove this test from quarantine at some point and we want to make sure we aren't forgetting about it
- We should have a spreadsheet to track quarantined tests, please talk to @evanilson-santana for this
   - Similar to the above point, we want to track our quarantined tests

Once you do all this, please forward this PR. In the future, please follow these instructions for future tickets.

**Comment by timpak** [comment]
@sirfabios, it's been a week and I haven't seen any movement on the ticket or this PR. I've left clear instructions in my previous comment and none of them were followed, I want an explanation during our next sync on Thursday.

@evanilson-santana, please follow up with Fabio to make sure this is completed.

**Comment by sirfabios** [comment]
https://docs.google.com/spreadsheets/d/1B2uV6WFcMx3--m1_3d5-dEz-r6SFzJv20MCH4D7CMO4/edit#gid=1052042255

**Pull request closed without merging**
