### PR TITLE
LPS-172288 Remove tests from quarantine

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
[LPS-172288](https://issues.liferay.com/browse/LPS-172288)

- LocalFile.WorkflowKnowledgeBaseArticle#CanApproveBasicChildArticleWhenParentPending
- LocalFile.WorkflowKnowledgeBaseArticle#ChildArticleStatusIsPendingAfterSubmitForWorkflow

Both tests area failing due to this [LPS-181652](https://issues.liferay.com/browse/LPS-181652).

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
ci:test:sf

**Comment by Luizcarlosqueiroz** [comment]
Hey @patriciajeanperez! I just updated the commit. Also, created the LPS-183572 inside the bug ticket.

**Comment by patriciajeanperez** [comment]
Thanks! @Luizcarlosqueiroz I updated the Quarantined/Ignored tests spreadsheet too.

**Comment by patriciajeanperez** [comment]
ci:forward

**Pull request closed without merging**
