### PR TITLE
LPS-170190 | master

### PR DESCRIPTION
**Pull request by chaowang-123**
https://issues.liferay.com/browse/LPS-170190

@timpak please review this, thanks!

### CODE REVIEW

**Comment by chaowang-123** [comment]
ci:test:sf

**Comment by evanilson-santana** [comment]
@chaowang-123 can you please fix these conflicts and pushed again? Thx

**Comment by chaowang-123** [comment]
ci:test:sf

**Comment by chaowang-123** [comment]
HI @evanilson-santana
Already fix the conflict, thanks!

**Comment by epark18** [comment]
@chaowang-123 Thank you for your work on this! LGTM

**Comment by epark18** [comment]
ci:forward

**Pull request closed without merging**
