### PR TITLE
LPS-176073 | Objects LXC Suite

### PR DESCRIPTION
**Pull request by JhossephG**
https://issues.liferay.com/browse/LPS-176073

### CODE REVIEW

**Comment by epark18** [comment]
ci:test:sf

**Comment by epark18** [comment]
@JhossephG Your commit messages need to begin with the ticket number.

**Comment by JhossephG** [comment]
ci:test:sf

**Review by timpak — APPROVED** [review]

**Comment by timpak** [comment]
ci:forward

**Pull request closed without merging**
