### PR TITLE
LPS-177975 | master

### PR DESCRIPTION
**Pull request by patriciajeanperez**
https://issues.liferay.com/browse/LPS-177975

### CODE REVIEW

**Comment by patriciajeanperez** [comment]
Hi @timpak, can you please check and see if you have any objections removing this line for our test suites. Thank you!

**Comment by timpak** [comment]
Looks like you want to run the quarantined tests on the test suite? Yeah that's fine with me, as long as we're tracking the failures on the spreadsheet.

**Comment by patriciajeanperez** [comment]
@timpak only the ones that were acceptance tests and then quarantined. Thanks for checking!

**Comment by patriciajeanperez** [comment]
ci:forward

**Pull request closed without merging**
