### PR TITLE
LPS-174030 | Test fix  | Master

### PR DESCRIPTION
**Pull request by abhnerramos**
My Ticket: 
https://issues.liferay.com/browse/LPS-174030

### CODE REVIEW

**Comment by abhnerramos** [comment]
ci:test:sf

**Review by Luizcarlosqueiroz — APPROVED** [review]
LGTM! :tada:

**Comment by Luizcarlosqueiroz** [comment]
ci:forward

**Comment by xbrianlee** [comment]
ci:forward

Looks like forward got stuck in the previous execution

**Pull request closed without merging**
