### PR TITLE
LPS-174862 | Automation | Master

### PR DESCRIPTION
**Pull request by thaiscabrals**
[ Remove the Asserts from the macros of the ObjectField.macro](https://issues.liferay.com/browse/LPS-174862)

- assertDocumentsAndMediaHomeFolderByCompany
- assertDocumentsAndMediaHomeFolderBySite
- assertLabel
- assertMandatory
- assertName
- assertNameDisabled
- assertOptionAndDescription
- assertSearchableLanguage
- assertSource
- assertTypeDisabled
- assertValueOnLimitCharactersNotPresent
- viewCountCharactersOnEntries

### CODE REVIEW

**Comment by thaiscabrals** [comment]
ci:test:sf

**Comment by epark18** [comment]
Great job on this @thaiscabrals! This is very helpful. I'm going to run the test suite just to double check.

**Comment by epark18** [comment]
ci:test:object

**Comment by epark18** [comment]
ci:forward
LGTM!

**Pull request closed without merging**
