### PR TITLE
LPS-174886 Refactor objects teardown to delete definitions with relationships

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
**Ticket:**
[LPS-174886](https://issues.liferay.com/browse/LPS-174886)

**Motivation:**
The Objects teardown does not work was intended when the Object has a relationship, that should be deleted before deleting the definition itself.
This can turn into a bigger problem if we have an unsuccessful run at CI, since it'll re-run in a not clean state. For example, we can see that at this particular printscreen, the test is running for the third time, adding a Layout for the same Object Definition that was not previously deleted:
before10

**Proposed Solution:**
Add a macro to the `ObjectAdmin#deleteAllCustomObjectsViaAPI` using available endpoints to delete all Relationships, regardless the parent being Custom or System.

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
ci:test:sf

**Comment by Luizcarlosqueiroz** [comment]
ci:test:object

**Comment by epark18** [comment]
ci:test:object

**Comment by epark18** [comment]
ci:test:sf

**Comment by epark18** [comment]
@Luizcarlosqueiroz sorry for the delay on this, I think this will need a rebase to fix the SF errors caused by the poshi regen last week.

**Comment by Luizcarlosqueiroz** [comment]
Hey @epark18 ! I was supposed do minor changes to this PR, but as I was in medical leave, I'll work on it this week.

**Comment by Luizcarlosqueiroz** [comment]
ci:test:sf

**Comment by Luizcarlosqueiroz** [comment]
ci:test:sf

**Comment by Luizcarlosqueiroz** [comment]
ci:test:object

**Review by timpak — APPROVED** [review]
LGTM! In the future, please use the label "Ready for Review" so that it's easier to keep track of PRs that are ready to be reviewed.

**Comment by timpak** [comment]
ci:forward

**Pull request closed without merging**
