### PR TITLE
LPS-187030 | Refactor | Master

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
**Ticket:** [LPS-187030](https://issues.liferay.com/browse/LPS-187030)

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
ci:test:sf

**Comment by Luizcarlosqueiroz** [comment]
ci:test:calendar

**Comment by Luizcarlosqueiroz** [comment]
ci:test:forms

**Comment by Luizcarlosqueiroz** [comment]
ci:test:object

**Comment by Luizcarlosqueiroz** [comment]
ci:test:workflow

**Comment by timpak** [comment]
This is the first time I've seen a PR with all of the component labels. Can we find a way to add the rest of them and complete the infinity gauntlet?? 👀

**Comment by patriciajeanperez** [comment]
ci:forward

**Pull request closed without merging**
