### PR TITLE
LPS-176849 | Test Automation | Master

### PR DESCRIPTION
**Pull request by davisaints**
**JIRA Ticket: [LPS-176849](https://issues.liferay.com/browse/LPS-176849)**

Resend of https://github.com/liferay-bpm-qa/liferay-portal/pull/542

### CODE REVIEW

**Comment by davisaints** [comment]
ci:test:sf

**Comment by davisaints** [comment]
ci:test:sf

**Comment by davisaints** [comment]
ci:test:sf

**Review by Luizcarlosqueiroz — APPROVED** [review]
LGTM :tada:

**Comment by epark18** [comment]
ci:forward

**Comment by davisaints** [comment]
ci:test:sf

**Comment by davisaints** [comment]
ci:forward

**Pull request closed without merging**
