### PR TITLE
LPS-182286 | Master

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
ci:test:sf

**Comment by Luizcarlosqueiroz** [comment]
ci:test:sf

**Comment by Luizcarlosqueiroz** [comment]
ci:test:calendar

**Comment by Luizcarlosqueiroz** [comment]
ci:test:calendar

**Comment by patriciajeanperez** [comment]
Superseded by https://github.com/liferay-bpm-qa/liferay-portal/pull/752

**Pull request closed without merging**
