### PR TITLE
New test suite| LPS-202926 | Master

### PR DESCRIPTION
**Pull request by evanilson-santana**
https://liferay.atlassian.net/browse/LPS-202926

### Motivation

The object component requests a new suite to run only integration tests in different databases. The idea is to analyze the test suite for each db environment to get specific fails.

### CODE REVIEW

**Comment by evanilson-santana** [comment]
ci:test:sf

**Comment by evanilson-santana** [comment]
ci:test:object-db-integration

**Review by timpak — APPROVED** [review]
LGTM!

**Comment by timpak** [comment]
ci:forward

**Comment by timpak** [comment]
We need to analyze the test failures before we can really use this test suite @evanilson-santana. Can you organize a task force to take a look into the failures on Friday?

**Pull request closed without merging**
