### PR TITLE
LPS-195309 | Master

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
**Tickets:** [LPS-195309](https://liferay.atlassian.net/browse/LPS-195309)

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
ci:test:object-db-partition:nocompile

**Comment by Luizcarlosqueiroz** [comment]
ci:test:object-as:nocompile

**Comment by Luizcarlosqueiroz** [comment]
ci:test:object-db:nocompile

**Comment by Luizcarlosqueiroz** [comment]
ci:test:object-db-partition:nocompile

**Comment by Luizcarlosqueiroz** [comment]
ci:test:object-db-partition

**Comment by Luizcarlosqueiroz** [comment]
ci:test:object-as

**Comment by Luizcarlosqueiroz** [comment]
ci:test:object-db

**Comment by patriciajeanperez** [comment]
@timpak @Luizcarlosqueiroz maybe we can get rid of object-environments?

**Review by timpak — COMMENTED** [review]
@Luizcarlosqueiroz can you include a commit to remove the old environments test suite? You can forward this afterwards, thanks!

Great job on this, btw.

**Comment by Luizcarlosqueiroz** [comment]
Hey @timpak @patriciajeanperez! I removed object-environments. Thanks!

**Comment by Luizcarlosqueiroz** [comment]
ci:forward

**Pull request closed without merging**
