### PR TITLE
LPS-175158 | Test Fix | Master

### PR DESCRIPTION
**Pull request by pedroamarall**
Ticket: 
https://issues.liferay.com/browse/LPS-175158

### CODE REVIEW

**Comment by pedroamarall** [comment]
ci:test:sf

**Comment by andreefarias** [comment]
Hey @pedroamarall, 

Could use another macro as `PortletEntry.publish();` to replace it? Validating the save is important for the Object.

**Comment by pedroamarall** [comment]
ci:test:sf

**Comment by andreefarias** [comment]
Hey @pedroamarall,

Could remove this commit: [LPS-175158 | Add the task's into the test](https://github.com/liferay-bpm-qa/liferay-portal/pull/490/commits/79fe745a88792440c290478e44953720fa9a6f9a)?

You can make the changes and run the SF. If generating a new commit, you may use the `amend` function to hide it. Let me know if you need help.

**Comment by andreefarias** [comment]
ci:forward

**Pull request closed without merging**
