### PR TITLE
LPS-158615 | master

### PR DESCRIPTION
**Pull request by kristinonias**
https://issues.liferay.com/browse/LPS-158615

### CODE REVIEW

**Comment by timpak** [comment]
@andreefarias can you take a first pass at this PR?

**Comment by andreefarias** [comment]
Hi @kristinonias,

thanks for your job, the testcase is clean and good to read! Macros will be very useful in the future.

**Comment by andreefarias** [comment]
Hey @timpak,

It's good for me! It was the first testcase via API that a reviewed and I understood the steps and return on the log.

**Comment by andreefarias** [comment]
ci:test:sf

**Comment by nikki-pru** [comment]
@timpak , is this ready to forward?

**Comment by rafaellajordao** [comment]
ci:forward

**Pull request closed without merging**
