### PR TITLE
LPS-176852 | master

### PR DESCRIPTION
**Pull request by liuxingye**
https://issues.liferay.com/browse/LPS-176852

### CODE REVIEW

**Comment by liuxingye** [comment]
ci:test:sf

**Comment by liuxingye** [comment]
This SF issue is not related to my changes, will retest it later.

**Comment by liuxingye** [comment]
ci:test:sf

**Comment by liuxingye** [comment]
ci:test:sf

**Comment by liuxingye** [comment]
ci:test:sf

**Comment by andreefarias** [comment]
So many tests separate related to Formula Field. I'll merge them all and send you a unique PR. Thanks!

**Comment by liuxingye** [comment]
@andreefarias thank you

**Comment by andreefarias** [comment]
ci:close

**Pull request closed without merging**
