### PR TITLE
LPS-187390 | Master

### PR DESCRIPTION
**Pull request by andreefarias**
Ticket: [LPS-187390](https://liferay.atlassian.net/browse/LPS-187390)

I updated a generic path that was used in the date and dateTime fields to avoid conflict when adding. For testcase I attach on dependences a new JSON file that contains more than 100 fields into the custom object.

### CODE REVIEW

**Comment by andreefarias** [comment]
ci:test:sf

**Comment by andreefarias** [comment]
ci:test:sf

**Comment by andreefarias** [comment]
ci:test:sf

**Comment by andreefarias** [comment]
ci:test:sf

**Comment by andreefarias** [comment]
ci:test:sf

**Comment by andreefarias** [comment]
Hey @timpak, I don't know why, but the ci:test:sf put only one label. Is there a problem?

**Comment by andreefarias** [comment]
ci:test:sf

**Review by timpak — APPROVED** [review]

**Comment by timpak** [comment]
ci:forward

**Comment by timpak** [comment]
ci:forward

**Comment by timpak** [comment]
ci:forward:force

**Pull request closed without merging**
