### PR TITLE
LPS-190167 | Test Fix | Master

### PR DESCRIPTION
**Pull request by Natanaelbenvindo**
Ticket: [LPS-190167](https://liferay.atlassian.net/browse/LPS-190167)
Added a gotoAdvancedTab step and improved the path

### CODE REVIEW

**Comment by Natanaelbenvindo** [comment]
ci:test:sf

**Comment by andreefarias** [comment]
ci:test:sf

**Comment by patriciajeanperez** [comment]
Hey @Natanaelbenvindo, you are updating a path that is being used by other tests. Did you run tests to make sure that they won't be affected by this change?

**Comment by patriciajeanperez** [comment]
@Natanaelbenvindo actually you didn't attach a passing test report for the test you are fixing either. Can you upload those in the ticket?

**Comment by Natanaelbenvindo** [comment]
Hey, @patriciajeanperez Patricia, I just attached the index to the ticket and tested the tests that also use this path and they passed.

**Review by timpak — APPROVED** [review]
At some point, we're going to have to refactor our paths but not today :see_no_evil:

**Comment by timpak** [comment]
ci:forward

**Comment by andreefarias** [comment]
ci:forward

**Pull request closed without merging**
