### PR TITLE
LPS-187647 | Salesforce Beta | Master

### PR DESCRIPTION
**Pull request by victorhcunha**
[LPS-187647](https://issues.liferay.com/browse/LPS-187647)

### CODE REVIEW

**Comment by victorhcunha** [comment]
**Tests on ci:**

- [LocalFile.ObjectSalesforce#AssertCRUDWithImportedStandardObject](https://testray.liferay.com/home/-/testray/case_results/2352758171?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2352755306%26testrayRunId%3D2352758103%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)
- [LocalFile.ObjectSalesforce#AssertCRUDWithImportedCustomObject](https://testray.liferay.com/home/-/testray/case_results/2352758159?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2352755306%26testrayRunId%3D2352758103%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)
- [LocalFile.ObjectSalesforce#AssertCRUDWithCreatedStandardObject](https://testray.liferay.com/home/-/testray/case_results/2352758140?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2352755306%26testrayRunId%3D2352758103%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)
- [LocalFile.ObjectSalesforce#AssertCRUDWithCreatedCustomObject](https://testray.liferay.com/home/-/testray/case_results/2352758114?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2352755306%26testrayRunId%3D2352758103%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)

**Comment by victorhcunha** [comment]
ci:test:sf

**Comment by victorhcunha** [comment]
ci:test:sf

**Review by timpak — APPROVED** [review]
LGTM!

**Comment by timpak** [comment]
ci:forward

**Pull request closed without merging**
