### PR TITLE
LPS-173384 | Test Fix | Master

### PR DESCRIPTION
**Pull request by victorhcunha**
Ticket:
https://issues.liferay.com/browse/LPS-173384

### CODE REVIEW

**Comment by victorhcunha** [comment]
ci:test:sf

**Comment by epark18** [comment]
@victorhcunha Great job on this. Could you attach test results onto the ticket based off your changes? Thanks!

**Comment by victorhcunha** [comment]
> @victorhcunha Great job on this. Could you attach test results onto the ticket based off your changes? Thanks!

Hi @epark18 , thanks! Now I attached the index file to the ticket

**Comment by andreefarias** [comment]
ci:forward

**Comment by andreefarias** [comment]
Great @victorhcunha!

Remember that change the status of the ticket. Thanks!

**Pull request closed without merging**
