### PR TITLE
LRQA-69476 | Test Automation | Master

### PR DESCRIPTION
**Pull request by jaydawu**
https://issues.liferay.com/browse/LRQA-69476
Submit for master only.

Hi team, please review. Thanks!

### CODE REVIEW

**Comment by jaydawu** [comment]
cc/ @timpak

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by evanilson-santana** [comment]
LGTM!

**Comment by evanilson-santana** [comment]
ci:forward

**Pull request closed without merging**
