### PR TITLE
LPS-146031 | Test Refactor | Master

### PR DESCRIPTION
**Pull request by naraandrade**
Related to: https://issues.liferay.com/browse/LPS-146031

### CODE REVIEW

**Comment by naraandrade** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
ci:test:relevant

**Review by Luizcarlosqueiroz — APPROVED** [review]
LGTM! :tada:

**Comment by Luizcarlosqueiroz** [comment]
ci:forward

**Comment by Luizcarlosqueiroz** [comment]
ci:close

**Comment by naraandrade** [comment]
Resent here: https://github.com/brianchandotcom/liferay-portal/pull/129674

**Pull request closed without merging**
