### PR TITLE
LPS-174983 | Test Fix | Master

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
**Ticket:** [LPS-174983](https://liferay.atlassian.net/browse/LPS-174983)

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
ci:test:sf

**Comment by patriciajeanperez** [comment]
@Luizcarlosqueiroz, we try to avoid having this assertion in macros now as it causes flaky failures and also because we do not need to assert the success message for all our tests. Have we confirmed it does fix the failing test? I am wondering why the other tests that use this macro are passing.

**Comment by Luizcarlosqueiroz** [comment]
Hey @patriciajeanperez!
I observed that the issue for this case was that the data was not being saved before the next function was run. The idea was to the portal have more time to load it. There are 4 other tests that use this macro, but 3 are ignored and the last one does not leave the Workflow page after clicking the Upgrade button. 
I added a new solution, instead of using the application menu, use just a back button. Locally it's working.

**Comment by patriciajeanperez** [comment]
ci:forward

**Pull request closed without merging**
