### PR TITLE
LPS-174830 - Refactor ObjectCustomViews.macro | Master

### PR DESCRIPTION
**Pull request by thaiscabrals**
[Remove the Asserts from the macros of the ObjectCustomViews.macro](https://issues.liferay.com/browse/LPS-174830)

- assertColumnLabelPresent
- assertColumnNotPresentOnAddColumnModal
- assertObjectViewName
- assertObjectViewNotPresent

### CODE REVIEW

**Comment by thaiscabrals** [comment]
ci:test:sf

**Comment by andreefarias** [comment]
Thanks, @thaiscabrals! 🎉

**Review by andreefarias — APPROVED** [review]
Good job, @thaiscabrals. Thanks! 🎉

**Comment by andreefarias** [comment]
ci:forward

**Pull request closed without merging**
