### PR TITLE
LRQA-72985 | Test Automation | Master

### PR DESCRIPTION
**Pull request by sirfabios**
https://issues.liferay.com/browse/LRQA-72985

### CODE REVIEW

**Comment by sirfabios** [comment]
ci:test:sf

**Comment by evanilson-santana** [comment]
ci:forward

**Comment by evanilson-santana** [comment]
Hey @sirfabios looks like your changes are failing some Poshi tests. Can you check your changes?

**Comment by sirfabios** [comment]
ci:test:sf

**Comment by andreefarias** [comment]
ci:forward

**Comment by evanilson-santana** [comment]
Hey @sirfabios can you check your changes and sent in another PR, please?

**Pull request closed without merging**
