### PR TITLE
LPS-190522 - Fix Automation | Calendar | Master

### PR DESCRIPTION
**Pull request by thaiscabrals**
**Ticket:** [LPS-190522](https://liferay.atlassian.net/browse/LPS-190522)
**Test:** ConfigurationTemplate#CanFilterByTemplateName

### CODE REVIEW

**Comment by thaiscabrals** [comment]
ci:test:sf

**Comment by thaiscabrals** [comment]
ci:test:sf

**Comment by thaiscabrals** [comment]
ci:test:sf

**Comment by patriciajeanperez** [comment]
@thaiscabrals can you update and make sure the correct commits are pushed?

**Pull request closed without merging**
