### PR TITLE
LPS-176818 | Add feature flag

### PR DESCRIPTION
**Pull request by davisaints**
Related issue: 

- [LPS-177475](https://issues.liferay.com/browse/LPS-177475)

### CODE REVIEW

**Comment by davisaints** [comment]
ci:test:sf

**Comment by davisaints** [comment]
ci:forward

**Comment by davisaints** [comment]
ci:close

**Comment by davisaints** [comment]
ci:reopen

**Comment by andreefarias** [comment]
ci:forward

**Pull request closed without merging**
