### PR TITLE
LPS-192016 | Quarantine | Master

### PR DESCRIPTION
**Pull request by andreefarias**
Ticket: [LPS-192016](https://liferay.atlassian.net/browse/LPS-192016)

Waiting for the fix of the bug.

### CODE REVIEW

**Comment by andreefarias** [comment]
ci:test:sf

**Comment by andreefarias** [comment]
ci:test:sf

**Comment by patriciajeanperez** [comment]
@andreefarias can we add these to the [spreadsheet](https://docs.google.com/spreadsheets/d/1B2uV6WFcMx3--m1_3d5-dEz-r6SFzJv20MCH4D7CMO4/edit#gid=1052042255)?

**Comment by andreefarias** [comment]
Yes, we can. I added them, thanks for the reminder @patriciajeanperez.

I didn't make it before because I was waiting for the merge.

**Comment by patriciajeanperez** [comment]
cool, thank you! @andreefarias

**Comment by patriciajeanperez** [comment]
ci:forward

**Pull request closed without merging**
