### PR TITLE
LPS-189377 | Test Fix | Master

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
**Ticket:** [LPS-189377](https://liferay.atlassian.net/browse/LPS-189377)

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
ci:test:sf

**Comment by Luizcarlosqueiroz** [comment]
ci:test:sf

**Comment by patriciajeanperez** [comment]
ci:forward

**Comment by patriciajeanperez** [comment]
ci:forward

**Comment by patriciajeanperez** [comment]
ci:forward

**Comment by patriciajeanperez** [comment]
ci:forward

**Comment by patriciajeanperez** [comment]
ci:forward

**Comment by patriciajeanperez** [comment]
ci:forward:force

**Comment by patriciajeanperez** [comment]
ci:forward:force

**Pull request closed without merging**
