### PR TITLE
LPS-178594 | Master

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
**Ticket:**
[LPS-178594](https://issues.liferay.com/browse/LPS-178594)
Create test suite with DB partition enabled for Forms, Workflow, and Data Engine

cc: @patriciajeanperez

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
ci:test:sf

**Comment by Luizcarlosqueiroz** [comment]
ci:test:data-engine-db-partition

**Comment by Luizcarlosqueiroz** [comment]
ci:test:forms-db-partition

**Comment by Luizcarlosqueiroz** [comment]
ci:test:workflow-db-partition

**Comment by patriciajeanperez** [comment]
ci:forward

**Pull request closed without merging**
