### PR TITLE
LPS-162176 | Test Automation | Master

### PR DESCRIPTION
**Pull request by JhossephG**
https://issues.liferay.com/browse/LPS-162176

### CODE REVIEW

**Comment by JhossephG** [comment]
ci:test:sf

**Comment by JhossephG** [comment]
ci:test:sf

**Review by timpak — APPROVED** [review]
@JhossephG Please see my changes [here](https://github.com/liferay-bpm-qa/liferay-portal/pull/103/commits/f834c4a3fe13a360ee73f0e7ca7cd7e65e96079c)

**Comment by timpak** [comment]
See https://github.com/liferay-bpm-qa/liferay-portal/pull/103

**Pull request closed without merging**
