### PR TITLE
LPS-179102 | Test Automation | Master

### PR DESCRIPTION
**Pull request by davisaints**
**JIRA Ticket: [LPS-179102](https://issues.liferay.com/browse/LPS-179102)**

### CODE REVIEW

**Comment by davisaints** [comment]
ci:test:sf

**Comment by andreefarias** [comment]
ci:forward:force

**Comment by andreefarias** [comment]
ci:stop

**Comment by andreefarias** [comment]
ci:forward:force

**Comment by andreefarias** [comment]
ci:stop

**Pull request closed without merging**
