### PR TITLE
LPS-181093 | Test fix | Master

### PR DESCRIPTION
**Pull request by alanafergs**
https://issues.liferay.com/browse/LPS-181093

### CODE REVIEW

**Comment by alanafergs** [comment]
The tests  `AddWCWithFirstComplexStructure` and `AddWCWithSecondComplexStructure` that use the macro `DataEngine.assertFieldRepeated` are failing, but not for that reason. So it would be good to do a deeper investigation to find out why.

**Comment by alanafergs** [comment]
ci:test:sf

**Comment by patriciajeanperez** [comment]
Hi @alanafergs, we cannot submit a change to a macro if we are going to break two tests that are currently passing. Before we submit this change, let's make sure all of the tests that use the macro will pass. Perhaps you can upload an html file so we can take a look and see why they are failing?

**Comment by Luizcarlosqueiroz** [comment]
This fix is touching the path that is being fixed by this other [PR](https://github.com/liferay-bpm-qa/liferay-portal/pull/769) as well

**Comment by patriciajeanperez** [comment]
I'll be closing this PR since the tests are fixed in https://github.com/liferay-bpm-qa/liferay-portal/pull/769. Let's work better next time in avoiding duplicates. @alanafergs good job with this fix but I'll go with https://github.com/liferay-bpm-qa/liferay-portal/pull/769 since the affected tests were ran with that fix already

**Pull request closed without merging**
