### PR TITLE
LPS-195162 | Refactor

### PR DESCRIPTION
**Pull request by victorhcunha**
[LPS-195162](https://liferay.atlassian.net/browse/LPS-195162)

### CODE REVIEW

**Comment by victorhcunha** [comment]
Using different values to variables between the tests is util to see from what tests are the inputs that pollute the salesforce object coming from

**Comment by victorhcunha** [comment]
ci:test:sf

**Comment by andreefarias** [comment]
LGTM! 🎉

**Comment by andreefarias** [comment]
ci:forward

**Pull request closed without merging**
