### PR TITLE
LPS-197446 | Delete testcase (no need) | Master

### PR DESCRIPTION
**Pull request by Natanaelbenvindo**
Test [LPS-197446](https://liferay.atlassian.net/browse/LPS-197446)
The read-only behavior of the field has changed by  [LPS-190903](https://liferay.atlassian.net/browse/LPS-190903)

### CODE REVIEW

**Comment by Natanaelbenvindo** [comment]
ci:test:sf

**Comment by andreefarias** [comment]
ci:test:sf

**Review by andreefarias — APPROVED** [review]

**Review by timpak — APPROVED** [review]
LGTM!

**Comment by timpak** [comment]
ci:forward

**Pull request closed without merging**
