### PR TITLE
LPS-163654 | Add testcase CanSeeLabelWhenEditingRelationship

### PR DESCRIPTION
**Pull request by bronsonsoda**
**CanSeeLabelWhenEditingRelationship**

Given: An object related to itself, in a Many-to-Many relationship
When: The user edits the relationships on the Relationship tab
Then: The relationship should have a label indicating whether it's the Parent or the Child

https://issues.liferay.com/browse/LPS-163659

### CODE REVIEW

**Comment by bronsonsoda** [comment]
I used a duplicate path , fixing soon

**Comment by bronsonsoda** [comment]
ci:help

**Comment by bronsonsoda** [comment]
ci:test:relevant

**Comment by epark18** [comment]
ci:stop

**Comment by bronsonsoda** [comment]
ci:test:sf

**Comment by bronsonsoda** [comment]
ci:test:relevant

**Comment by epark18** [comment]
Hey @bronsonsoda, sorry for the delay on this one. Could you SF, rebase, and resend this. Thank you

**Comment by bronsonsoda** [comment]
@epark18 yes sir

**Pull request closed without merging**
