### PR TITLE
LPS-168098

### PR DESCRIPTION
**Pull request by Natanaelbenvindo**
https://issues.liferay.com/browse/LPS-168098

### CODE REVIEW

**Comment by thaiscabrals** [comment]
ci:test:sf

**Comment by thaiscabrals** [comment]
ci:test:objects

**Comment by thaiscabrals** [comment]
ci:test:object

**Comment by epark18** [comment]
ci:test:object

**Comment by epark18** [comment]
Test results look good to me. Thanks for your solution on this @Natanaelbenvindo!

**Comment by epark18** [comment]
ci:forward

**Pull request closed without merging**
