### PR TITLE
LPS-180833 | Add test ViewObjectFieldAfterUpgrade7413U33

### PR DESCRIPTION
**Pull request by bronsonsoda**
https://issues.liferay.com/browse/LPS-180833

### CODE REVIEW

**Comment by epark18** [comment]
ci:test:sf

**Review by epark18 — COMMENTED** [review]
Great job @bronsonsoda

**Comment by epark18** [comment]
ci:test:object

**Comment by epark18** [comment]
test failures should resolve once you change the test name for the skip portal instance @bronsonsoda

**Comment by bronsonsoda** [comment]
ci:test:object

**Comment by bronsonsoda** [comment]
ci:stop

**Comment by bronsonsoda** [comment]
ci:test:object

**Comment by bronsonsoda** [comment]
ci:stop

**Comment by bronsonsoda** [comment]
ci:test:object

**Comment by timpak** [comment]
Hey @bronsonsoda, is this ready for review?

**Review by timpak — APPROVED** [review]

**Comment by timpak** [comment]
ci:forward

**Comment by bronsonsoda** [comment]
ci:test:sf

**Comment by bronsonsoda** [comment]
ci:forward

**Pull request closed without merging**
