### PR TITLE
LPS-192323  | Test Fix | Master

### PR DESCRIPTION
**Pull request by sirfabios**
https://liferay.atlassian.net/browse/LPS-192323

### CODE REVIEW

**Comment by sirfabios** [comment]
ci:test:sf

**Comment by timpak** [comment]
@sirfabios this path is used very heavily in our tests, did you test this to make sure it doesn't break our existing tests?

**Comment by sirfabios** [comment]
Hey @timpak 
- I couldn't find any path that finds exactly this place.
- I tested yes, I sent the index in the ticket

**Comment by timpak** [comment]
@sirfabios did you try using `MenuItem#ANY_MENU_ITEM`?

**Comment by timpak** [comment]
@sirfabios please see my comment and complete this by the end of the week. If this isn't doable, then please contact me.

**Pull request closed without merging**
