### PR TITLE
LPS-169442 | Test Fix | Master

### PR DESCRIPTION
**Pull request by victorhcunha**
[LPS-169442](https://issues.liferay.com/browse/LPS-169442)

### CODE REVIEW

**Comment by victorhcunha** [comment]
ci:test:sf

**Comment by patriciajeanperez** [comment]
@victorhcunha looks like the test was originally failing because of a missing PDF file. Were you able to reproduce that?

**Comment by victorhcunha** [comment]
@patriciajeanperez 
The error on ci is really different from the local error
I will close this PR until I have another correction alternative

**Comment by victorhcunha** [comment]
ci:close

**Pull request closed without merging**
