### PR TITLE
LPS-180748 | Test Fix | Master

### PR DESCRIPTION
**Pull request by davicms**
[Element is not present in MyWorkflowTasks#ResubmitTaskByDetails](https://issues.liferay.com/browse/LPS-180748)

### CODE REVIEW

**Comment by epark18** [comment]
ci:test:sf

**Comment by epark18** [comment]
@davicms Thanks for the fix, but remember to attach test results on the ticket. Need confirmation the test fix is passing.

**Comment by epark18** [comment]
SF will fail because of your commit message, btw. It needs to have a ticket associated with it.

**Comment by davicms** [comment]
ci:test:sf

**Comment by epark18** [comment]
looks good!

**Comment by epark18** [comment]
ci:forward

**Pull request closed without merging**
