### PR TITLE
LPS-196448 | Testfix | Master

### PR DESCRIPTION
**Pull request by mateussandes23**
https://liferay.atlassian.net/browse/LPS-196448

### CODE REVIEW

**Comment by mateussandes23** [comment]
ci:test:sf

**Comment by andreefarias** [comment]
ci:forward

**Comment by patriciajeanperez** [comment]
Hi @mateussandes23 Can we make sure we add a passing index.html next time? Thanks!

**Comment by patriciajeanperez** [comment]
ci:forward

**Pull request closed without merging**
