### PR TITLE
LPS-190242 |  Test fix | Master

### PR DESCRIPTION
**Pull request by Natanaelbenvindo**
[LPS-190242](https://liferay.atlassian.net/browse/LPS-190242)
From my investigation, this test is failing because the "View" button has changed to "Edit". To solve the problem I made a change in the test to "Edit".

### CODE REVIEW

**Comment by Natanaelbenvindo** [comment]
ci:test:sf

**Comment by JhossephG** [comment]
ci:test:sf

**Review by timpak — APPROVED** [review]
@Natanaelbenvindo in the future, try to use more informative commit messages. We understand that you're fixing the test but it's unclear what exactly how you're fixing it. Using a message like the one below is a lot more descriptive and clearly explains what you're doing.

`Select Edit instead of View in the dropdown menu`

**Comment by timpak** [comment]
ci:forward

**Pull request closed without merging**
