### PR TITLE
LPS-173359 | Test Fix | Master

### PR DESCRIPTION
**Pull request by JhossephG**
https://issues.liferay.com/browse/LPS-173359

### CODE REVIEW

**Comment by JhossephG** [comment]
ci:test:sf

**Comment by epark18** [comment]
@JhossephG Can you add the test results on the ticket?

**Comment by JhossephG** [comment]
> @JhossephG Can you add the test results on the ticket?

Done!

**Comment by epark18** [comment]
ci:forward

**Pull request closed without merging**
