### PR TITLE
LPS-151541 Remove the testing quarantine

### PR DESCRIPTION
**Pull request by thaiscabrals**
https://issues.liferay.com/browse/LPS-151541
https://issues.liferay.com/browse/LPS-164332

### CODE REVIEW

**Comment by thaiscabrals** [comment]
ci:test:sf

**Comment by thaiscabrals** [comment]
ci:forward

**Comment by thaiscabrals** [comment]
ci:stop

**Comment by evanilson-santana** [comment]
@thaiscabrals new PR [here](https://github.com/liferay-bpm-qa/liferay-portal/pull/18)

**Pull request closed without merging**
