### PR TITLE
LRQA-74762 | Master

### PR DESCRIPTION
**Pull request by davisaints**
**JIRA Ticket: [LRQA-74762](https://liferay.atlassian.net/browse/LRQA-74762)**

### CODE REVIEW

**Comment by davisaints** [comment]
ci:test:sf

**Comment by davisaints** [comment]
Hey @patricia jean perez, feel free to review it. I'll send it forward as soon as [this one](https://github.com/liferay-bpm-qa/liferay-portal/pull/971) is merged.

**Comment by patriciajeanperez** [comment]
LGTM! @davisaints

**Comment by davisaints** [comment]
ci:forward

**Comment by davisaints** [comment]
ci:forward

**Pull request closed without merging**
