### PR TITLE
LPS-169475 | Test Fix | Master

### PR DESCRIPTION
**Pull request by victorhcunha**
[LPS-169475](https://issues.liferay.com/browse/LPS-169475)

### CODE REVIEW

**Comment by victorhcunha** [comment]
ci:close

**Comment by victorhcunha** [comment]
ci:reopen

**Comment by victorhcunha** [comment]
ci:test:sf

**Comment by victorhcunha** [comment]
ci:test:sf

**Review by timpak — APPROVED** [review]

**Pull request closed without merging**
