### PR TITLE
LPS-183868 | Test Fix | Master

### PR DESCRIPTION
**Pull request by davisaints**
**JIRA Ticket: [LPS-183868](https://issues.liferay.com/browse/LPS-183868)**

### CODE REVIEW

**Comment by davisaints** [comment]
ci:test:sf

**Comment by davisaints** [comment]
ci:test:sf

**Review by timpak — APPROVED** [review]
@davisaints please remember to provide context on the ticket as to why you're fixing this. You need to explain the outcome of your investigation and how you're going to fix the issue. Without this context, it's hard for others to understand what happened in the ticket.

**Comment by timpak** [comment]
ci:forward

**Pull request closed without merging**
